### ISSUE TITLE
No provider for IterableDiffers! (NgFor -> IterableDiffers)

### ISSUE THREAD

**Issue by pvadam** [PointInside/ng2-toastr#1]
```No provider for IterableDiffers! (NgFor -> IterableDiffers)``` exception when the component is injected into a service. This is a bug in angular 2. See [issue #4330 here](https://github.com/angular/angular/issues/4330).

The workaround is easy, PR is on the way.

@derekshi, Please also add the gulp file to the project, since it is referenced in the scripts section of the package.json!

**Comment by derekshi** [comment]
Done.

**Comment by pvadam** [comment]
Thanks!
