### ISSUE TITLE
Error : Cannot read property 'vcRef' of undefined

### ISSUE THREAD

**Issue by Pinank** [PointInside/ng2-toastr#101]
I have just shifted my project to angular-cli and started getting following error.

TypeError: Cannot read property 'vcRef' of undefined at http://localhost:4200/main.bundle.js

TypeError: Cannot read property 'vcRef' of undefined at http://localhost:4200/main.bundle.js:65026:101 at new ZoneAwarePromise (http://localhost:4200/main.bundle.js:109811:29)   at ToastsManager.show (http://localhost:4200/main.bundle.js:65017:16)    at ToastsManager.error (http://localhost:4200/main.bundle.js:65105:21)    at eval (eval at evaluate (:117:21), <anonymous>:1:19)↵    at HttpService.onSubscribeError (http://localhost:4200/main.bundle.js:6041:9)    at SafeSubscriber._error (http://localhost:4200/main.bundle.js:5868:19)    at SafeSubscriber.__tryOrSetError (http://localhost:4200/main.bundle.js:583:16)    at SafeSubscriber.error (http://localhost:4200/main.bundle.js:539:26)    at Subscriber._error (http://localhost:4200/main.bundle.js:479:26)

It was working fine previously.

Thanks in advance..

**Comment by prasadjasti** [comment]
I am also facing the same issue.

**Comment by albertosetim** [comment]
I am also facing the same issue.

**Comment by derekshi** [comment]
```
constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
        this.toastr.setRootViewContainerRef(vRef);
    }
```

This doesn't solve your problem?

**Comment by albertosetim** [comment]
Yes perfect..

**Comment by ZenabKhan** [comment]
I think it is not related to angular-cli. It was was working fine but then got the same error when I upgraded my angular version from **2.1.0** to **2.2.0**

**Comment by Pinank** [comment]
Yes, Got the solution. Place in your root component

    constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
            this.toastr.setRootViewContainerRef(vRef);
        }

for more detail refer following link 

https://github.com/PointInside/ng2-toastr#breaking-change-solution-for-angular-v22x

**Comment by k1ng440** [comment]
i did as readme but still i am getting the error

**Comment by ZenabKhan** [comment]
@k1ng440 have you added the code in root component?

**Comment by k1ng440** [comment]
@ZenabKhan i was loading it to shared module that was causing the issue. i solved it by adding it to root module.

ty
