### ISSUE TITLE
Cannot find SourceMap 'ng2-toastr.js.map'

### ISSUE THREAD

**Issue by IlyaSurmay** [PointInside/ng2-toastr#102]
Hi! Lib works fine but I get warnings in the console like: 
`Cannot find SourceMap 'ng2-toastr.js.map'`
`Cannot find SourceMap 'toast-container.component.js.map'`
etc
Please add source maps to package. I know that I can get rid of these errors by removing lines like that one `//# sourceMappingURL=toast.module.js.map` but changing external lib in node_modules isn't the best option, also it's bad because my app bundles on Azure and I don't want to remove these lines after every `npm install` there. Thanks!

**Comment by derekshi** [comment]
I think it's warning from chrome browser. You may want to build project using `webapck` or `angular-cli`, which is recommended way to work on angular project.
