### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by umasgn** [PointInside/ng2-toastr#103]
While i was using this package in angular 2 + webpack project, got this error.

**Comment by derekshi** [comment]
exclude ng2-toastr.js from your html `script` tag.

**Comment by umasgn** [comment]
Thanks man it worked. Thank you very much for your quick response.

**Comment by ivanlopezmolina** [comment]
Hi I'm getting the same error in angular 4, I added this in the .angular-cli.json

`"scripts": ["../node_modules/ng2-toastr/bundles/ng2-toastr.min.js"],`

regards,
