### ISSUE TITLE
How can i move the ng2-toastr into a service to be used by all components

### ISSUE THREAD

**Issue by joelmuskwe** [PointInside/ng2-toastr#113]
I moved my logic to a services as below:

import {Injectable, ViewContainerRef} from '@angular/core';
import { ToastsManager } from 'ng2-toastr/ng2-toastr'

@Injectable()
export class NotificationsService {
  constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
    this.toastr.setRootViewContainerRef(vRef);
    console.log(vRef.element);
  }

  showSuccess(header: any, description: any) {
    this.toastr.success(description, header);
  }

  showError(header: any, description: any) {
    this.toastr.error(description, header);
  }

  showWarning(header: any, description: any) {
    this.toastr.warning(description, header);
  }

  showInfo(header: any, description: any) {
    this.toastr.info(description, header);
  }
}

but getting an error: 

inline template:0:0 caused by: No provider for ViewContainerRef!
Error: No provider for ViewContainerRef!

**Comment by marcovdb** [comment]
You should move the setRootViewContainer code into your main app component.

**Comment by joelmuskwe** [comment]
Thank you works like a charm,

**Comment by chule143** [comment]
Hi @joelmuskwe, please help!!!, I'm getting this error when I tried to use the service to show the toastr:

`Error: No provider for ToastsManager! `

I have the "ToastsManager" into the app.component.ts and the shared.service.ts , also I tried the @marcovdb  solution

**Comment by derekshi** [comment]
in your `app.module` class:
use `ToastsModule.forRoot()` instead of `ToastsModule`.

**Comment by chule143** [comment]
Thanks @derekshi !!, now works!!, but I'm get this message:

`Error encountered resolving symbol values statically. Calling function 'ToastModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`

In the /src/app/app.module.ts file
