### ISSUE TITLE
ToastOptions properties are declared as required

### ISSUE THREAD

**Issue by StevenLiekens** [PointInside/ng2-toastr#115]
The TypeScript definitions for `ToastOptions` declares all properties as required. This is incorrect. They should be declared as optional.

**Comment by marcovdb** [comment]
That's weird...

https://github.com/PointInside/ng2-toastr/commit/5a582d064d180855263f87c4c5fc131a2bccf685

**Comment by derekshi** [comment]
guys, try v1.3.4 now.
