### ISSUE TITLE
Can't use AoT because of requirement for abstract class ViewContainerRef

### ISSUE THREAD

**Issue by GenZodd** [PointInside/ng2-toastr#117]
This required code causes AoT to blow up.

 `constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
        this.toastr.setRootViewContainerRef(vRef);
    }`

Error: Error at D:/project/compiled/src/app/app.module.ngfactory.ts:397:79: Cannot create an instance of the abstract class 'ViewContainerRef'.

Will probably have to go away from this until it can work with AoT but there are a few issues logged against this for AoT.

**Comment by StevenLiekens** [comment]
Did you put that code in the AppModule or the AppComponent? I think that's what that error is about.

**Comment by GenZodd** [comment]
That code is in my AppComponent pure the read me. The way you phrased that it is unclear if that is what you expected so for good measure I put it into AppModule but that did not work.
