### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by nofear87** [PointInside/ng2-toastr#120]
````
zone.js:1561 GET http://localhost:3000/ng2-toastr 404 (Not Found)
customers:25 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-toastr
Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-toastr
````

I got the following errors...is there something what I have to add to systemjs.config?

I use Angular 2.3.

**Comment by redplane** [comment]
Same question for this one :|

**Comment by nofear87** [comment]
@redplane did you use systemjs? Then try adding 'ng2-toastr': 'npm:ng2-toastr' to the map. That solves my problems.
