### ISSUE TITLE
1.3.7 and 1.4.0 error loading module

### ISSUE THREAD

**Issue by blackholegalaxy** [PointInside/ng2-toastr#125]
# Bug
After having updated to 1.3.7 or 1.4.0, I encounter an error at build time:

> ERROR in Error encountered resolving symbol values statically. Calling function 'ToastModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in app.module.ts, resolving symbol AppModule in app.module.ts

Also encountering in my component the TS error:

![error_ts](https://cloud.githubusercontent.com/assets/11064123/22393043/9293bab0-e4ce-11e6-9bf1-f00efc2b5714.png)

## app.module.ts
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,

    ToastModule.forRoot(),

    // Routing
    RouterModule.forRoot(ROUTES, { useHash: false, preloadingStrategy: PreloadAllModules }),
  ],
  providers: [ ],
  bootstrap: [AppComponent]
})
```

## Tried to solve by doing this
- Tried to remove `.forRoot()` in `app.module.ts`
- Build OK
- Still have error in console:

> Unhandled Promise rejection: No provider for ToastsManager! ; Zone: angular ; Task: Promise.then ;

## **Rolling back to `1.3.3` works fine**

**Comment by born2net** [comment]
same issue...

**Comment by wolfgangteves** [comment]
Same here

**Comment by derekshi** [comment]
Try v1.4.1. It should fix `angular-cli` issue.

**Comment by wolfgangteves** [comment]
Sorry, still seems to not work. Getting this error when upgrading to 1.4.1

![bildschirmfoto 2017-01-31 um 09 53 24](https://cloud.githubusercontent.com/assets/22980179/22458148/688c69d6-e79b-11e6-8c43-88a00be59e56.png)

**Comment by psaussure** [comment]
Same problem here even with 1.4.1

**Comment by derekshi** [comment]
Use `ToastModule.forRoot()` when importing. And are you guys using `angular-cli`? Not the same issue with #126 ?

**Comment by psaussure** [comment]
I used for my part ToastModule.forRoot() and angular-cli beta 26. Error is still showing up. Tried to reinstall all the modules and clean cache.

**Comment by james-knerr** [comment]
I am using angular-cli beta 28.3 and have tried version 1.3.3, 1.3.7, and 1.4.1 of ng2-toastr and nothing seems to fix this issue.

**Comment by james-knerr** [comment]
Any updates on how to get around this issue?

**Comment by derekshi** [comment]
Hi guys, not sure if it's still an issue for you. I added a demo app using ng-cli beta 32.0. It seems to work without any issues.

**Comment by james-knerr** [comment]
Just updated to 32 and it works perfect. Your demo was a helpful reference thanks!
