### ISSUE TITLE
Version 1.4.0 breaks

### ISSUE THREAD

**Issue by santanu-biswas** [PointInside/ng2-toastr#127]
Everything was working fine with version 1.3.7.

Upgraded to version 1.4.0 today and it stopped working. I get the following error while compiling:

> ERROR in Error encountered resolving symbol values statically. Calling function 'ToastModule', function calls are not supported.
>  Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in...

Looks like it is caused by the changes in `forRoot` method of `ToastModule` because removing `forRoot()` solves the problem however for obvious reasons it is followed by the error `No provider for ToastsManager!`

Reverting back to version 1.3.7 makes it work again.

**Comment by santanu-biswas** [comment]
Tested this a bit more and found that it does not work with `angular-cli` based project. Since you are testing it with `systemjs` project and `webpack` project, hence you don't see the error.

**Comment by broweratcognitecdotcom** [comment]
"Reverting back to version 1.3.7 makes it work again."

Same problem with fresh install today. Thank you Santanu.

**Comment by efstathiosntonas** [comment]
same here on angular 2.4.5

**Comment by santanu-biswas** [comment]
The problem is basically with the code inside static `.forRoot()` method. The `.forRoot()` method cannot use static values. It should be passed a `factory`. There is another challenge. The initial config is to be optional. In version 1.4.0 it is being handled by testing if `config` is defined and accordingly using `providers.push` method to pass the `ToastOptions` provider. This too will not work. it needs to be handled with conditional return statement.

I could figure out a solution and tested at my end with `systemjs`, `webpack` demo and also added a `angular-cli` demo. The solution is to modify the `.forRoot()` method (in `toast.module.ts`) as:

```
static forRoot(optionsFactory?: any): ModuleWithProviders {
        return optionsFactory ? {
            ngModule: ToastModule,
            providers: [ToastsManager, { provide: ToastOptions, useFactory: optionsFactory  }],
        } :
        {
            ngModule: ToastModule,
            providers: [ToastsManager],
        };
}
```

This is the only change required. Now depending on whether global options requires changes he AppModule should include the following:

**Case-1** (_use default global options_)

```
@NgModule({
    imports: [
        BrowserModule,
        ToastModule.forRoot(),
    ],
    declarations: [AppComponent],
    bootstrap: [AppComponent],
})
export class AppModule { }
```

**Case-2** (_modify one or more default options_)

```
export function toastrOptionsFactory(): any {
    return {
        toastLife: 5000,
        showCloseButton: true,
        enableHTML: true
    };
};

@NgModule({
    imports: [
        BrowserModule,
        ToastModule.forRoot(toastrOptionsFactory),
    ],
    declarations: [AppComponent],
    bootstrap: [AppComponent],
})
export class AppModule {}
```

In fact this is how some other popular packages (e.g. `ng2-translate`) are also handling initial loaders.

I have done the required changes in code and if the repo admin/members agree, I can submit a PR (includes a `angular-cli` version of the demo)

**Comment by derekshi** [comment]
Try v1.4.1. It should fix `angular-cli` issue.

**Comment by santanu-biswas** [comment]
@derekshi I have updated to v1.4.1 and it works fine now. Thanks for your help. You can close this issue.

I also had a look at the code change in `toast.module.ts` and I was wondering if the `ToastModule.forRoot()` can be made flexible to accept static configuration or a factory. OR... is it possible to add a `setToastOptions` function to `ToastManager` (can be called where `setRootViewContainerRef` function is called). This is helpful if I am using `ng2-toastr` for a project that has multiple sub-applications inside it and each sub-application has its own independent set of configurations.

**Comment by derekshi** [comment]
@santanu-biswas The scenario you described can be done using dependency injection. There might be some examples described in other closed issues. You can check it out. Basically, you want to make your sub-application different module and inject a new instance of `ToastsManager` into each module.
