### ISSUE TITLE
prevent duplicate error issue

### ISSUE THREAD

**Issue by sharmilemurugaraj** [PointInside/ng2-toastr#13]
I am using ng2-toastr module, how to set prevent duplicate to true i.e I dont want to display same message multiple times.

Can you explain how to make this?

**Comment by derekshi** [comment]
There is no easy way built in yet but if you set maxDisplay = 1, it would only display one message at a time. Another way is you can fork the library and update logic of Toast-Container.component.ts to make a list of unique 'toasts'.

**Comment by sharmilemurugaraj** [comment]
okay sure I will fork the library now

**Comment by derekshi** [comment]
@sharmilemurugaraj FYI: since ng2-toastr v1.2.0, all 'show' methods return `Promise<Toast>`. So you can have your own logic to check if any new toast will be duplicate.
