### ISSUE TITLE
Breaking change solution for Angular v2.2.x is not working 

### ISSUE THREAD

**Issue by yzimmermann** [PointInside/ng2-toastr#131]
Fix

 `constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
        this.toastr.setRootViewContainerRef(vRef);
    }`

is not working :(

Angular 2.4.4 - ng2-toastr 1.4.1 and 1.3.x

**Comment by AndreasKuhlmann** [comment]
Same problem here. Using Angular2 v2.4.0

**Comment by jkyoutsey** [comment]
ng 2.4.7 and ng2-toaster 1.4.1 it works fine for me.

**Comment by UlricW** [comment]
Same issue. Using ng 2.4.7 and ng2-toastr 1.4.1 as @jkyoutsey proposed not solved the problem 

here is the chrome console error: "Error: Please set root ViewContainerRef using setRootViewContainerRef(vRef: ViewContainerRef) method.
Error: Please set root ViewContainerRef using setRootViewContainerRef(vRef: ViewContainerRef) method. "

app.component: 

` constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
    this.toastr.setRootViewContainerRef(vRef);
  }`

**Comment by andreagrossetti** [comment]
If you get no errors and toastr is not displayed probably you haven't included the css.

**Comment by UlricW** [comment]
I just found the problem for me,

It was a silly error, a request was sended before that the setRootViewContainerRef was done, so an error happened.

**Comment by mauricio1992jzr** [comment]
@yzimmermann  Good afternoon friend, did you manage to solve this problem?
