### ISSUE TITLE
Error on build with angular 4.0.0-beta.7

### ISSUE THREAD

**Issue by KevinGruber** [PointInside/ng2-toastr#132]
I get the following error on building with prod and with aot since angular 4 update.

Do you know what the problem could be?

BR,
Kevin

ERROR in Can't resolve all parameters for ToastOptions in D:/__PRODUCTS/drReports/node_modules/ng2-toastr/src/toast-options.d.ts: (?).

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\__PRODUCTS\drReports\src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts

**Comment by k-schneider** [comment]
I'm seeing this issue as well - doesn't matter if aot flag is present when building or not.  If you install ng2-toastr into an Angular 4 project generated by @angular/cli and run this it will fail:

`ng build --target=production`

**Comment by derekshi** [comment]
Sorry for late response, but try following code: 
```
@Injectable()
export class CustomOption extends ToastOptions {
  constructor() {
    super({
      animate: 'flyRight', // you can pass any options to override defaults
      newestOnTop: false,
      showCloseButton: true,
    });
  }
}

@NgModule({
  declarations: [ ... ],
  imports: [
     ...
    ToastModule.forRoot(),
  ],
  providers: [{provide: ToastOptions, useClass: CustomOption }],
  bootstrap: [ ... ]
})
```

**Comment by artaommahe** [comment]
@derekshi same error with `class CustomOption`

**Comment by derekshi** [comment]
Ok, updated to v1.5.0. Tested with `angular v4.0.0-beta.8` and `angular-cli v1.0.0-beta.32.3`. Please follow the `readme` to use custom global options.

**Comment by artaommahe** [comment]
@derekshi works well, thx
