### ISSUE TITLE
newestOnTop as global setting

### ISSUE THREAD

**Issue by JPtenBerge** [PointInside/ng2-toastr#133]
Hi there,

I would like to have the toasts showing up with the newest on top, but at the moment that's a setting I have to pass along with every individual toast. It would be awesome if this could be configured once during startup, like in the AppComponent:

```
export class AppComponent {
	constructor(
		private toastr: ToastsManager,
		private vcr: ViewContainerRef
	) {
		this.toastr.setRootViewContainerRef(vcr);
		this.toastr.config({ newestOnTop: true } as ToastConfig);
	}
}
```

Also: Thanks for the work so far, awesome toastr support, loving the animations.

**Comment by derekshi** [comment]
You should define your global configuration in module definition. (see README.md)
