### ISSUE TITLE
Build error with custom toast options

### ISSUE THREAD

**Issue by enghelewa** [PointInside/ng2-toastr#139]
I tried to make my custom class but got a build error says:
```
Types of property 'dismiss' are incompatible.
Type 'string' is not assignable to type '"auto" | "click" | "controlled"'.
```

This is my custom class
```
import {ToastOptions} from 'ng2-toastr';

export class ToasterOptions extends ToastOptions {
    positionClass = 'toast-bottom-right';
    maxShown = 5;
    newestOnTop = false;
    animate = 'flyRight';
    toastLife = 50000;
    enableHTML = true;
    messageClass = '';
    dismiss = "click";
    titleClass = '';
    showCloseButton = false;
}
```

**Comment by derekshi** [comment]
@enghelewa good catch. Please use v1.5.1.

**Comment by chriseenberg** [comment]
i still get errors saying supplied parameters do not match, with version 1.5.1 of toastr

`showInfo(msg: string, title: string) {
        let options = new ToastOptions({
            animate: 'flyRight',
            toastLife: 5000,
        });
        this.toastr.info(msg, title, options)
    }`

Any pointers to what might be causing this?

Kind regards - Chris

**Comment by derekshi** [comment]
@chriseenberg : simply pass in an object instead of instance of `ToastOptions`. Since v1.5.1, `ToastOptions` does not support this type of instantiation. 

```
this.toastr.info(msg, title, { animate: 'flyRight', toastLife: 5000, })
```

**Comment by zakhenry** [comment]
I was able to solve this with
```ts
// my notification service
export const GLOBAL_TOAST_OPTIONS: ToastOptions = {
  animate: 'flyRight', // you can override any options available
  newestOnTop: false,
  showCloseButton: true,

  // defaults
  positionClass: 'toast-bottom-right',
  toastLife: 5000,
  maxShown: 5,
  enableHTML: true,
  dismiss: 'auto',
  messageClass: "",
  titleClass: ""
};
```

and

```ts
//app.module.ts
ToastModule.forRoot(GLOBAL_TOAST_OPTIONS),
```

**Comment by derekshi** [comment]
@zakhenry : yes, your solution works for v1.4.x and before. In v1.5.x, it won't work anymore.

**Comment by zakhenry** [comment]
@derekshi hmm, pretty sure I'm using v1.5.1, though I'm mid-battle with migrating from angular-seed to angular-cli so I can't say for sure that it works as the app is not running yet, but the error has gone away

**Comment by derekshi** [comment]
@zakhenry : ok, you may be right. Probably you are not using angular-cli. `ng build -prod` may fail.
