### ISSUE TITLE
Errors after updating to Angular2 beta 16

### ISSUE THREAD

**Issue by Yoanribeiro** [PointInside/ng2-toastr#14]
Hello there,

First of all thank you for the lib, it's great!
I am using it in my Angular 2 project and it worked like charm, however after I updated Angular 2, the lib started to give me compile errors[1], and the JS console on the browsers, after using the toastr, also gave an error[2].
Anyone else with the same problem? 
Thanks in advance 

[1]
```
/node_modules/ng2-toastr/src/toast-manager.ts(29,31): error TS2339
 Property 'resolve' does not exist on type 'typeof Injector'.
/node_modules/ng2-toastr/src/toast-manager.ts(33,54): error TS2345
 Argument of type 'ElementRef' is not assignable to parameter of type 'ViewContainerRef'.
  Property 'element' is missing in type 'ElementRef'.
/node_modules/ng2-toastr/src/toast-manager.ts(68,20): error TS2339
 Property 'dispose' does not exist on type 'ComponentRef'.
```

[2]
`TypeError: c.Injector.resolve is not a function
EXCEPTION: TypeError: c.Injector.resolve is not a function
STACKTRACE:
TypeError: c.Injector.resolve is not a function
`

**Comment by vaags** [comment]
I too get these errors. It seems that beta 16 brought quite a few breaking changes - not all documented in the change log.

**Comment by derekshi** [comment]
Make sure download the latest version of ng2-toastr '0.1.10'.

**Comment by Yoanribeiro** [comment]
@vaags updating the module solved the problem for me! 
Thank you very much @derekshi !

**Comment by vaags** [comment]
Great! The update solved it for me as well. This issue can be closed, I think :)
