### ISSUE TITLE
TypeError: Cannot read property '_hostElement' of undefined(…)

### ISSUE THREAD

**Issue by chandandas** [PointInside/ng2-toastr#15]
I receive "TypeError: Cannot read property '_hostElement' of undefined(…)" when i call
 this.toastr.success('You are awesome!', 'Success!'); inside constructor.

and following error if i call on button shown as in example

TypeError: Cannot read property 'resolve' of undefined(…)

**Comment by derekshi** [comment]
You can't put this `this.toastr.success()` in constructor because when instantiating the component, the component or the app views are not built yet. Make sure views are built before calling this. Another way is to use setTimeout to make a 500ms or 1s delay.

**Comment by chandandas** [comment]
Thanks. What i did now is just copied the entire code in example you specified and pasted into my app. When i click the button, i received error saying "TypeError: Cannot read property 'resolve' of undefined(…)", can you please help me.

**Comment by derekshi** [comment]
How do you setup the app component? Are you using angular 2.0beta.16?

**Comment by chandandas** [comment]
using 2.0.0-beta.15

**Comment by derekshi** [comment]
upgrade to beta.16.
