### ISSUE TITLE
Cannot find module '@angular/animations/browser'. Angular 4.0.0

### ISSUE THREAD

**Issue by elnobun** [PointInside/ng2-toastr#150]
Hello,

Please I am using Angular 4.0.0. I followed the instructions for installing ng2-toastr, to make it compatible for the latest Angular 4.0 But I get the following error:

```
Failed to compile.

/usr/src/app/node_modules/@angular/platform-browser/animations/src/animation_renderer.d.ts 
(1,53): Cannot find module '@angular/animations/browser'.)
```

I am not quite sure what is wrong. Every Other thing seems fine. Thanks in advance.

**Comment by derekshi** [comment]
Can you check demo/ngcli example and see if anything you are missing? Have you included AnimationModule?

**Comment by elnobun** [comment]
Yes @derekshi, I have and that is what baffles me. I followed the steps again as I am writing to you, and still the same issue. 

thanks for your kind response.

**Comment by elnobun** [comment]
Ok! I had to manually install `@angular/animations` as a dependency, and that fixed the issue. Thanks for your patience @derekshi. I will be closing this issue now.
