### ISSUE TITLE
Add support for ng5 

### ISSUE THREAD

**Issue by born2net** [PointInside/ng2-toastr#151]
getting this error when doing AOT with current project:

```
in C:/msweb/studioweb/node_modules/ng2-toastr/src/toast-options.d.ts: (?). This will become an error in Angular v5.x
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
```

**Comment by bruno-barros** [comment]
Same here after update to Angular 4.0.0 and angular-cli@latest

```
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///AlertModule/AlertComponent.html@1:0
```

**Comment by derekshi** [comment]
Are you guys sure it's an issue with ng2-toastr? If you run demo/ngcli app in `ng build -aot`, there is no issues.

**Comment by bruno-barros** [comment]
@derekshi My fault bout AOT. I'm running with a regular `ng serve`
Take a look:

![untitled-1](https://cloud.githubusercontent.com/assets/1840784/24572933/93022656-1653-11e7-8324-2e5cab8cb42c.png)

**Comment by derekshi** [comment]
@bruno-barros this is not a warning from ng2-toastr. it's from` AlertModule` you are using.

**Comment by bruno-barros** [comment]
humm I'm sorry. It's from ng2-bootstrap.

**Comment by TINITUS** [comment]
@bruno-barros & @born2net, check your code for <template> el. You need to replace it with <ng-template> if you are on ng v.4 and above.

**Comment by bruno-barros** [comment]
@TINITUS I haven't any. It's from ng2-bootstrap AlertModule. I did remove it and the message gone.

**Comment by TINITUS** [comment]
@bruno-barros, shure, it is still to update for ng 4+

**Comment by born2net** [comment]
tx for the support, it was from ngx-bootstrap
