### ISSUE TITLE
positionClass is not working

### ISSUE THREAD

**Issue by dilotec-2015** [PointInside/ng2-toastr#156]
positionClass: 'toast-top-center'; is not working when i put it into CustomOptions.

export class CustomOptions extends ToastOptions {
  animate = 'fade';
  dismiss = 'click';
  positionClass: 'toast-top-center';
  showCloseButton = true;
  newestOnTop = true;
}

the other options are working well.

ng2-toastr: 1.6.0
Angular 2.4.8

**Comment by derekshi** [comment]
use `=` instead of `:`

**Comment by dilotec-2015** [comment]
thanks 👍
