### ISSUE TITLE
When used in akveo/ng2-admin, the CSS is not taken into account

### ISSUE THREAD

**Issue by LucasBrazi06** [PointInside/ng2-toastr#159]
Hello,

I use the akveo/ng2-admin dashboard framework and when using the toastr, the message is shown without the CSS, displaying it in a simple old unformated text.

Do you have any idea how to get your CSS working in this framework?

Thanks,
Serge.

**Comment by jdsmitty** [comment]
`@import "../../node_modules/ng2-toastr/ng2-toastr.css";`

This worked for me.
