### ISSUE TITLE
Problem with Custom Options on Angular v4

### ISSUE THREAD

**Issue by simonupcall** [PointInside/ng2-toastr#162]
I followed the example given for the custom configurations. 

Here is my config:
~~~
export class CustomOption extends ToastOptions {
  enableHTML: true;
  positionClass: 'toast-bottom-right';
  toastLife: 4000;
}
~~~

I have exactly the same config in the app.module with the provider and the import.

When I check the ToastManager, I get:

![toastmanageroptions](https://cloud.githubusercontent.com/assets/26075714/25253656/ab679bbc-25d6-11e7-9126-3781995fcb14.png)

My versions are Angular : 4.0.2 and ng2-toastr : 4.0.1

Do you have any idea about what I am doing wrong ? Or is it a bug?

**Comment by 255kb** [comment]
Same problem here, added a bunch of custom parameters and they are not loaded. 
I use same version of angular 2 with ng CLI 1.0.0

**Comment by derekshi** [comment]
@simonupcall @255kb : Be sure to use `=` not `:` to assign value to a class property. You are not defining an object here.

**Comment by 255kb** [comment]
Thanks it's working, and I am ashamed 😊
