### ISSUE TITLE
Error with 1.6 and Angular 4.3.6

### ISSUE THREAD

**Issue by M-R-Bishop** [PointInside/ng2-toastr#209]
Getting this error when running my project:

Uncaught (in promise): Error: The animation trigger "inOut" has failed to build due to the following errors:
 - The provided timing value "0.2s 10 ease-out" is invalid.
 - The provided timing value "0.2s 10 ease-out" is invalid.
 - The provided timing value "0.3s 10 ease-out" is invalid.
 - The provided timing value "0.3s 10 ease-out" is invalid.
 - The provided timing value "0.3s 10 ease-out" is invalid.
Error: The animation trigger "inOut" has failed to build due to the following errors:
 - The provided timing value "0.2s 10 ease-out" is invalid.
 - The provided timing value "0.2s 10 ease-out" is invalid.
 - The provided timing value "0.3s 10 ease-out" is invalid.
 - The provided timing value "0.3s 10 ease-out" is invalid.
 - The provided timing value "0.3s 10 ease-out" is invalid.

**Comment by snetty** [comment]
also experiencing this with both 1.6 and 4.1.2

**Comment by M-R-Bishop** [comment]
excuse my ignorance here, but what do you mean by 4.1.2?  The Angular version?  For some reason I'm still seeing this with 4.3.6 libraries (animation included).

**Comment by konuch** [comment]
I believe he meant ng2-toastr v4.1.2

**Comment by M-R-Bishop** [comment]
I realized my ng2Toastr version wasn't at 4.12.  After updating to the latest version this seems to be fixed for me.
