### ISSUE TITLE
Cannot find module '@angular/core'

### ISSUE THREAD

**Issue by triplejberger** [PointInside/ng2-toastr#21]
*npm start* throws `node_modules/ng2-toastr/src/toast-manager.d.ts(1,70): error TS2307: Cannot find module '@angular/core'.`

this is fixed by renaming `'@angular/core';` to `'angular2/core';`
and
`container: ComponentRef<any>;` to `container: ComponentRef;`
in *toast-manager.d.ts*

**Comment by derekshi** [comment]
make sure you are using angular v2.00rc.1. that's a breaking change that angular release candidates make.

**Comment by mgolois** [comment]
can these changes be pushed to npm. 
the package in npm is still using 'angular2/core' instead of  '@angular/core'

**Comment by derekshi** [comment]
Which version of beta are you using? You can specify different version of this library. Any v0.1 version supports "angular/core"

**Comment by derekshi** [comment]
I believe this is something to do with the project setup rather than an issue with this lib. Close the issue now.

**Comment by omeryounus** [comment]
I am having issue in IntelliJ when building the project.

Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
(4, 60): Cannot find module 'ng2
-material'.
'F:/ProjectA/tmp/broccoli_type_script_compiler-input_base_path-y1eRF234.tmp/0/src/app/shared/index.ts' is not a module.

any idea why I am getting the above error?
