### ISSUE TITLE
Can't use this library from service.

### ISSUE THREAD

**Issue by maximtitovich** [PointInside/ng2-toastr#218]
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Please set root ViewContainerRef using setRootViewContainerRef(vRef: ViewContainerRef) method.
Error: Please set root ViewContainerRef using setRootViewContainerRef(vRef: ViewContainerRef) method.

**Comment by maximtitovich** [comment]
Works fine, if you inject this._toaster.setRootViewContainerRef(_vRef); in root app components constructor. Would be better if done automaticly.

**Comment by Anujmoglix** [comment]
I did it by sample but facing that same issue . Can you @maximtitovich guide me to resolve this issue ?
