### ISSUE TITLE
Error: Uncaught (in promise)

### ISSUE THREAD

**Issue by triplejberger** [PointInside/ng2-toastr#22]
I'm copying `ng2-toastr.min.js` and `ng2-toastr.min.css` to my build folder and mapping ng2-toastr to `lib/ng2-toastr.min.js`. See index.html below:
```
<link href="lib/ng2-toastr.min.css" rel="stylesheet" />
    <script src="lib/ng2-toastr.min.js"></script>

    <!-- 2. Configure SystemJS -->
    <script>
      System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        },
        map: {
          "ng2-toastr": "lib/ng2-toastr.min.js",
        }
      });
```

In my component I import ToastsManager via `import {ToastsManager} from 'ng2-toastr';` and also add `    providers: [ToastsManager]`.
This is how my constructor looks like: `constructor(public toastr: ToastsManager) { }`

If I run the app I see the following error msg: `Error: Uncaught (in promise): Cannot resolve all parameters for 'Component'(undefined). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Component' is decorated with Injectable.`

PS: I also needed to change some things to get this far as mentioned in issue #21.

How do I get this going?

**Comment by derekshi** [comment]
@triplejberger have you resolved issue? Make sure you check system.js for correct config file loading.

**Comment by henritoivar** [comment]
Hey! Had the same issue. Here is how i resolved it:

My system.js configuration: 
```
const map: any = {
  // this might be different for you depending how you include files
  'ng2-toastr': 'vendor/ng2-toastr', 
};

/** User packages configuration. */
const packages: any = {
  'ng2-toastr': {
    defaultExtension: 'js'
  },
};
```
My component: 
```
import {Component, OnInit} from '@angular/core';
// I was importing from 'ng2-toastr'. Correct is 'ng2-toastr/ng2-toastr'
import {ToastsManager} from 'ng2-toastr/ng2-toastr'; 

@Component({
  moduleId: module.id,
  selector: 'app-dashboard',
  templateUrl: 'dashboard.component.html',
  styleUrls: ['dashboard.component.css'],
  providers: [ToastsManager]
})
export class DashboardComponent implements OnInit {

  constructor(protected toast:ToastsManager) {
  }

  ngOnInit() {
    this.toast.success('Hello dog', 'Booya!');
  }
}
```
