### ISSUE TITLE
Toastr notifications do not display

### ISSUE THREAD

**Issue by DylanRothko** [PointInside/ng2-toastr#220]
The implementation works fine, I don't get any errors in my components but i never see any notifications.  I'm following the implementation from the example exactly.  I'm running angular 4.4.5 and cli 1.4.7 currently, is this the cause of the notifications not displaying?

**Comment by GuidoNeele** [comment]
Experiencing the same behavior. I'm running Angular 4.3.6 and Angular CLI 1.3.0.

**Comment by GuidoNeele** [comment]
This solved my issue https://stackoverflow.com/questions/45584723/ng2-toastr-not-working-in-angular-2

**Comment by DylanRothko** [comment]
@GuidoNeele Thanks a ton, i gave that a try and it didn't make any difference though

**Comment by GuidoNeele** [comment]
Are you perhaps setting this.toastr.setRootViewContainerRef() multiple times?

**Comment by DylanRothko** [comment]
@GuidoNeele good thought but nope, I'm only setting it once in my app component.  My app is fairly large so i've tried it in a few other places but with no luck.  As far as I can see no new html is ever added to the DOM, unless its super buried.

**Comment by emp3ror** [comment]
add "../node_modules/ng2-toastr/bundles/ng2-toastr.min.css" on styles property of .angular-cli.json. notification shows but doesnt fade out

**Comment by DylanRothko** [comment]
@emp3ror thank!  This worked.
