### ISSUE TITLE
Using ng2-toastr with webpack

### ISSUE THREAD

**Issue by likerRr** [PointInside/ng2-toastr#23]
Hi, I have an angular2 project built with webpack. When I add `ng2-toastr` import it doesn't work because requires `System.js`, but I don't have it and I don't want to install.

So, how can I use `ng2-toastr` with webpack?

**Comment by derekshi** [comment]
You are right. Current build only supports systemjs. You may fork the library and build the library with webpack yourself.

**Comment by likerRr** [comment]
It's not so convenient... Do you plan to add non build system dependent builds?

**Comment by BrainCrumbz** [comment]
Do you guys know what is needed in order to create a webpack-enabled package? 

Opening the source, one can see there's already a `webpack.config.js` and at a quick (non-package-expert) look it seems ok.

**Comment by aarnaud** [comment]
+1

**Comment by BrainCrumbz** [comment]
BTW we tried copying TS source code and CSS into a project directory, as if it was just our custom code: build went fine and running gave no console errors, but actually no toast was showing. Sorry, we dropped this for now. Thanks to the authors for their effort!

**Comment by SathishRaju** [comment]
We seriously need webpack support!

**Comment by SathishRaju** [comment]
@BrainCrumbz btw, i copied the source into our project directory. Initially it did not give any notifications. Then realized i needed to include the css file as well. After including the css, it worked well.

**Comment by MikeLallemont** [comment]
Any ideas when the map files issue will be resolved? I had this working in web pack at least two version ago but since upgrading to version 2 cannot use it anymore. Is there a work around?

**Comment by baderbuddy** [comment]
This change in my PR should be an easy way to allow webpack support https://github.com/PointInside/ng2-toastr/pull/31

**Comment by derekshi** [comment]
Upgraded angular2 to rc.4. And updated ng2-toastr.js file on root folder, which can be used for webpack to bundle everything together with your apps. try out v0.3.0 and see if works for you guys.

**Comment by MikeLallemont** [comment]
Thanks you sir! Awesome work!
