### ISSUE TITLE
npm does not get the latest version of ng2-toastr library

### ISSUE THREAD

**Issue by mgolois** [PointInside/ng2-toastr#26]
npm does not get the latest version of ng2-toastr library

**Comment by derekshi** [comment]
0.2.0 should be on npm.

**Comment by mgolois** [comment]
it says it has the latest version (0.2.0) but when I compare the source code, it's totally different

**Comment by hxlniada** [comment]
yes, there is no .ts files，lead to errors when loading packages via webpack

**Comment by derekshi** [comment]
Is it still a problem with v0.3.0 above?
