### ISSUE TITLE
Build 0.1.8 assign error

### ISSUE THREAD

**Issue by hakalb** [PointInside/ng2-toastr#27]
I am trying to install 0.1.8 since I use Angular2 beta 12 for now.
I get compile error:

`Build: Property 'assign' does not exist on type 'ObjectConstructor'`

Any ideas what causing this?

**Comment by derekshi** [comment]
Have you solved the problem? I believe there's something to do with your project setup rather than this library. Let me know if I can close this issue.

**Comment by hakalb** [comment]
I found another library that worked that I am using now. Thanks anyway.
