### ISSUE TITLE
Failed to load 

### ISSUE THREAD

**Issue by emalmbor** [PointInside/ng2-toastr#30]
I got 2 errors:
Error loading http://localhost:5555/node_modules/@angular/package.json
Error loading http://localhost:5555/node_modules/ng2-toastr/src/toast-manager.js as "./src/toast-manager" from http://localhost:5555/node_modules/ng2-toastr/ng2-toastr.js "Report this error at https://github.com/mgechev/angular2-seed/issues"

Installed lastest version from npm. Changed @angular to angular2 in toast-manager.d.ts and still failed.  Any ideas??

**Comment by derekshi** [comment]
I haven't worked with seed project but it seems to me is your project setup issue. I am closing this issue now.
