### ISSUE TITLE
Failed to load @angular/core/src/linker/view_container_ref 

### ISSUE THREAD

**Issue by AndreiL13** [PointInside/ng2-toastr#32]
Hi guys,

I'm getting this error when I'm importing the ng2_toastr in my app 

> Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:56580/@angular/core/src/linker/view_container_ref

These are my dependencies:

>  "dependencies": {
	    "angular2": "2.0.0-beta.17",
        "@angular/common": "2.0.0-rc.1",
		"@angular/compiler": "2.0.0-rc.1",
		"@angular/core": "2.0.0-rc.1",
	    "@angular/http": "2.0.0-rc.1",
		"@angular/platform-browser": "2.0.0-rc.1",
		"@angular/platform-browser-dynamic": "2.0.0-rc.1",
		"@angular/router": "2.0.0-rc.1",       	
        "es6-promise": "^3.0.2",
        "es6-shim": "^0.35.0",
		"systemjs": "0.19.24",
        "reflect-metadata": "0.1.2",
        "rxjs": "5.0.0-beta.6",
        "zone.js": "0.6.12",	
        "bootstrap": "^3.3.6"		
    },

Also, I'm getting this error when running npm install 

> Not compatible with your operating system or architecture: fsevents@1.0.12

Cheers

**Comment by derekshi** [comment]
have you tried to upgrade all of your angular2 to latest version?

**Comment by AndreiL13** [comment]
It appears to be an issue with my systemjs config, because if I start adding the .js extension to all dependencies, the errors went away but new ones were created for the dependencies of the first dependencies and so on. I couldn't get it to work, so I used another toastr library
