### ISSUE TITLE
Allow optional configuration per message

### ISSUE THREAD

**Issue by damienpontifex** [PointInside/ng2-toastr#33]
For some messages, I'd like to be able to set `autoDismiss: false` but not as the default behaviour. An example being an alert I want to make certain the user has seen and dismisses.

Currently it seems we can only configure options at the top level in `bootstrap`. Could an optional parameter be added to the messages for options?

i.e. a signature like
```typescript
error(message: string, title?: string, options?: {}): void
```

**Comment by Vexra** [comment]
This would be really great. Another use case: I would like to set `toastLife` based on the length of the message, as a 3 word message and a 20 word message require a different time to be read.

**Comment by derekshi** [comment]
Latest v0.4.1 (supports rc.6) now allow custom options on individual toast and html toast.

**Comment by damienpontifex** [comment]
Awesome stuff. Tested and works beautifully :)
