### ISSUE TITLE
Creating toasts programmatically causes toasts to stack and not vanish properly.

### ISSUE THREAD

**Issue by l2thet** [PointInside/ng2-toastr#34]
When creating toasts programmatically, if I create more than one toast, the toasts will end up stacking on top of each other and the first toast in the stack will become a permanent fixture on the page. My work around was to use setTimeout on the each toast message, this would cause the toasts to sequence correctly below each other. Example [here](https://embed.plnkr.co/OT2iZHz98wSYMsr1ThDU/).

This seems like it might be related to [this](https://github.com/CodeSeven/toastr/issues/90)? I attempted to use the clearToast() method but ran into the same issue noted in the first paragraph.

The example also reflects the current version of ng2-toastr on npm, as well as the latest version of Angular 2. I include bootstrap but confirmed that the error still happens without bootstrap.

**Comment by derekshi** [comment]
mmm, I cannot reproduce the issue. Updated library to rc6 and I also included a demo app. Please check it out and see whether this is still an issue for you.
