### ISSUE TITLE
ng2-toastr.ts in same folder as d.ts.

### ISSUE THREAD

**Issue by cocytus** [PointInside/ng2-toastr#35]
I'm fairly new to TypeScript, so this might be something I have to configure differently, but:

When compiling a project which references ng2-toastr and using the typescript outFile parameter with the systemjs module system, the compiler outputs the source of ng2-toastr into my project. This also causes all module names to be relative to the root folder of my visual studio solution, so the ng2-toastr module is called "node_modules/ng2-toastr/ng2-toastr" instead of just "ng2-toastr".

The solution is probably to keep the .d.ts and .ts source files in separate folders. Either move .ts into a "src" folder, or move all .d.ts/.js files to the "bundles" folder.

**Comment by derekshi** [comment]
Not sure you have configured typescript correctly. In latest version 0.4.0 with rc6, I added a demo in the library. Please check it out.

**Comment by ronzeidman** [comment]
+1 having issues too with tsc + outdir:
```
error TS6059: File 'client/node_modules/ng2-toastr/src/toast-container.component.ts' is not
 under 'rootDir' 'client/src'. 'rootDir' is expected to contain all source files.
error TS6059: File '-client/node_modules/ng2-toastr/src/toast-manager.ts' is not under 'root
Dir' 'client/src'. 'rootDir' is expected to contain all source files.
error TS6059: File 'client/node_modules/ng2-toastr/src/toast-options.ts' is not under 'root
Dir' 'client/src'. 'rootDir' is expected to contain all source files.
error TS6059: File 'client/node_modules/ng2-toastr/src/toast.ts' is not under 'rootDir' 'client/src'. 'rootDir' is expected to contain all source files.
```
if you add outdir to your demo you will get the same result. So in order to not lose the ability to use .map files you have to "outdir" the transpiled files yourself so they won't be on the same folder.

**Comment by derekshi** [comment]
What does your tsconfig.json file look like?

**Comment by ronzeidman** [comment]
```json
    "compilerOptions": {
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "noEmitOnError": true,
        "noImplicitAny": false,
        "rootDir": "./src",
        "sourceMap": true,
        "target": "es5",
        "outDir": "dist/",
    },
```

**Comment by derekshi** [comment]
Mmm, I don't have any issues with outDir. Do you have the latest typescript installed? Also, I am not sure why you want to compile ng2-toastr together with your app if you set up following documentation. If you build with webpack, you just need to import ng2-toastr.d.ts into your entry ts files.

**Comment by ronzeidman** [comment]
I don't *want* to compile ng2-toastr tsc/ts-loader just does it (typescript 1.8.10/2.0.0) have you tried it when the root dir doesn't contain node_modules folder? Anyway I'll try creating a small test lib that will fail.
Thanks

**Comment by derekshi** [comment]
Generally, you should exclude all node_modules libraries. add
```
 "exclude": [
    "node_modules"
  ]
```
to your tsconfig.json file.

**Comment by ronzeidman** [comment]
Excluding libraries doesn't work if they are referenced:
Similarly, if a file B.ts is referenced by another file A.ts, then B.ts cannot be excluded unless the referencing file A.ts is also specified in the "exclude" list.
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
(Also I've experienced it so I'm not just saying)

**Comment by derekshi** [comment]
So I guess you are building with webpack. You should import all the referenced library to your entry level ts files. https://angular.io/docs/ts/latest/guide/webpack.html . Then you can exclude node_modules folder.

**Comment by ronzeidman** [comment]
This is a reproduction: https://github.com/ronzeidman/open-ng2-tests
to run it:
```
git clone https://github.com/ronzeidman/open-ng2-tests.git
npm i
npm run compile (this will fail)
npm start
```
The compile phase will not fail if you manually delete all .ts (except .d.ts) files from ng2-toastr in node_modules, otherwise it will try to compile them and give these errors:
```
ERROR in C:\open-ng2-tests\node_modules\ng2-toastr\src\toast-container.component.ts
(29,15): error TS7006: Parameter 'options' implicitly has an 'any' type.

ERROR in C:\open-ng2-tests\node_modules\ng2-toastr\src\toast-container.component.ts
(62,11): error TS7006: Parameter 'toast' implicitly has an 'any' type.

ERROR in C:\open-ng2-tests\node_modules\ng2-toastr\src\toast-manager.ts
(19,15): error TS7006: Parameter 'options' implicitly has an 'any' type.

ERROR in C:\open-ng2-tests\tsconfig.json
error TS6059: File 'C:/open-ng2-tests/node_modules/ng2-toastr/src/toast-container.component.ts' is not under 'rootDir' 'C:/open-ng2-tests/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\open-ng2-tests\tsconfig.json
error TS6059: File 'C:/open-ng2-tests/node_modules/ng2-toastr/src/toast-manager.ts' is not under 'rootDir' 'C:/open-ng2-tests/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\open-ng2-tests\tsconfig.json
error TS6059: File 'C:/open-ng2-tests/node_modules/ng2-toastr/src/toast-options.ts' is not under 'rootDir' 'C:/open-ng2-tests/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\open-ng2-tests\tsconfig.json
error TS6059: File 'C:/open-ng2-tests/node_modules/ng2-toastr/src/toast.module.ts' is not under 'rootDir' 'C:/open-ng2-tests/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\open-ng2-tests\tsconfig.json
error TS6059: File 'C:/open-ng2-tests/node_modules/ng2-toastr/src/toast.ts' is not under 'rootDir' 'C:/open-ng2-tests/src'. 'rootDir' is expected to contain all source files.

ERROR in ./src/bootstrap.ts
Module build failed: Error: Typescript emitted no output for C:\open-ng2-tests\src\bootstrap.ts
    at Object.loader (C:\open-ng2-tests\node_modules\ts-loader\index.js:456:15)
```
notice that the tsconfig contains:
```
"files": [
    "src/bootstrap.ts"
  ],
  "exclude": ["node_modules"]
```
and even the webpack ts-loader has:
```
            {
                test: /\.ts$/,
                loaders: [
                    'ts-loader'
                ],
                include: [path.resolve(__dirname, 'src')]
            }
```

**Comment by ronzeidman** [comment]
Notice that in issue #45 the no implicit any issue means that the typescript tries to compile the files from the source, It wouldn't have happen if the typescript compiler would have just took the compiled .js files instead. If you were to put the .ts files in a different folder the "import" wouldn't have been ambiguous and it wouldn't have tried to re-compile the sources.

I forgot to thank you for sharing this library and all the hard work you are putting. Other than this issue this library works perfectly and evolving fast with every angular2 release. Thanks

**Comment by derekshi** [comment]
I got it. I will try to remove ts files from next npm release. That should solve the problem.

**Comment by derekshi** [comment]
Please try out new release 0.4.3, which I took out all the ts files.

**Comment by ronzeidman** [comment]
Works great for me. Thanks.
Although there is n issue with some bundlers (like the jspm one) that have issues bundling with source maps where source maps don't exist but are referenced like for example in the ng2-toastr.js  at line 10 -  `//# sourceMappingURL=ng2-toastr.js.map`. Doesn't cause any issue for me (since I've abandoned jspm in favor of webpack) but it may be an issue for other people.

**Comment by derekshi** [comment]
So are you suggesting I should keep js.map files?

**Comment by ronzeidman** [comment]
I'm suggesting to either move the compiled files to a different dir and keep the ts and map files or compile without source maps and npmignore the ts files.
