### ISSUE TITLE
Not working with webpack

### ISSUE THREAD

**Issue by cybrown** [PointInside/ng2-toastr#37]
This project does not work with webpack, is it especially made only for systemjs ? Or can I configure my build for this lib to work ?

**Comment by derekshi** [comment]
If you import ng2-toastr.ts or ng2-toastr.js to your project directly, you should be able to build with webpack.

**Comment by cybrown** [comment]
Thanks for the replay, I've tried both `import {ToastOptions} from "ng2-toastr/ng2-toastr.ts";` and `import {ToastOptions} from "ng2-toastr/ng2-toastr.js";` but none of them work.

**Comment by derekshi** [comment]
The right way to do it is put following line into your boot.ts file:
```
import 'ng2-toastr/ng2-toastr.js';
import 'ng2-toastr/bundles/ng2-toastr.min.css';
```

And build with your webpack. And use ng2-toastr as documented.

**Comment by derekshi** [comment]
An example of webpack config.js:
```
var webpack = require('webpack');

module.exports = {
  entry:  {
    myApp: './src/boot.ts',
  },
  output: {
    path: './public/js',
    filename: '[name].min.js',
  },
  devtool: '#source-map',
  resolve: {
    extensions: ['', '.js', '.ts'],
  },
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loader: 'ts',

        //exclude: [/src\/ark/],
      },
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader',
      },
    ],
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      minimize: true,
      compress: { warnings: false },
    }),
  ],
};
```

Hope this helps.

**Comment by cybrown** [comment]
It helps but I still need to `import {ToastOptions} from "ng2-toastr/ng2-toastr";` for type checks, should I exclude the ng2-toastr modules somewhere in the configuration ?

**Comment by derekshi** [comment]
If you have ng2-toastr under your node_modules folder, it should be able to find ng2-toastr.d.ts file directly. I don't think there is extra configuration you need. Do you find the type def file in the folder?

**Comment by cybrown** [comment]
There is a typedef, it works, but when I import it, webpack adds the systemjs file. What I need to do is exclude this specific file or module from the generated webpack bundle.

**Comment by derekshi** [comment]
I don't understand why webpack would add systemjs file. Are you using typescript? do you have other dependencies that use systemjs internally?

**Comment by cybrown** [comment]
Yes I'm using typescript, through ts-loader.
Webpack adds the file because I use this import statement: `import {ToastOptions} from "ng2-toastr/ng2-toastr";`.

**Comment by derekshi** [comment]
It can't be. the `import` statement should only reads ng2-toastr.d.ts file in typescript. I believe there is something else messing up your webpack.

**Comment by cybrown** [comment]
Well, webpack reads this import (or the require when typescript transpiles it) and uses it to include the file build for systemjs. It's how webpack works, that's why I need to exclude this file.

However, is it possible to have a UMD file, so this lib won't be tied to systemjs ?

**Comment by cybrown** [comment]
The main issue is that System is not defined, even when I only `import 'ng2-toastr/ng2-toastr.
Is it mandatory to include the system.js library in my project ?

**Comment by derekshi** [comment]
which version of ng2-toastr are you using? should be using '0.3.0' or above. and there should be no system.js required.

**Comment by ashotik** [comment]
I could run the toastr via webpack successfully  but still getting 'ng2-toastr.min.js:1 Uncaught ReferenceError: System is not defined' in the console. When I include System.js the error  disappears. I am using 0.3.1 version

**Comment by derekshi** [comment]
if you build everything with webpack, you should not include 'ng2-toastr.min.js' on your html. Include the one built by webpack.

**Comment by cybrown** [comment]
Sorry replying this late and letting this issue open all those days, I've tried on a new project and I have to admit that it works perfectly fine.
I only had to import the css file, since the js file is automaticaly imported when we grab the ToastsManager service.

Thanks a lot for your replies.
