### ISSUE TITLE
Error after update RC6

### ISSUE THREAD

**Issue by hoangnguyenba** [PointInside/ng2-toastr#45]
Hi there,
I got these error after update rc6. I am using version 0.4.2
/node_modules/ng2-toastr/src/toast-container.component.ts(29,15): error TS7006: Parameter 'options' implicitly has an 'any' type.
/node_modules/ng2-toastr/src/toast-container.component.ts(62,11): error TS7006: Parameter 'toast' implicitly has an 'any' type.
/node_modules/ng2-toastr/src/toast-manager.ts(19,15): error TS7006: Parameter 'options' implicitly has an 'any' type.
/node_modules/ng2-toastr/src/toast-manager.ts(28,44): error TS7017: Index signature of object type implicitly has an 'any' type.

**Comment by derekshi** [comment]
are you using typescript v2.0.2? Upgrade the version if you are not. Then try follow the setup in demo app. (demo/).

**Comment by hoangnguyenba** [comment]
Yes, I am using typescript v2.02.
I switch off 'noImplicitAny' and it's working now.
I tried to fix myself, but I can't fix the last line:
/node_modules/ng2-toastr/src/toast-manager.ts(28,44): error TS7017: Index signature of object type implicitly has an 'any' type.
Can you show me how to fix in case I need switch on 'noImplicitAny'

**Comment by derekshi** [comment]
This probably requires some changes on source library. I will try to update later. Thanks for the information.

**Comment by derekshi** [comment]
Ok, version 0.4.3 should solve 'noImplicitAny' issue. But you need to turn on `'suppressImplicitAnyIndexErrors' : true` in tsconfig.json due to some hacks into angular2 core lib.
