### ISSUE TITLE
This is not working using WebPack

### ISSUE THREAD

**Issue by sagarjumble** [PointInside/ng2-toastr#46]
Error Shown : Uncaught Can't resolve all parameters for ToastContainer: (?, ToastOptions).
Can you please assist  me

**Comment by derekshi** [comment]
Can you provide more information? how your project is configured using webpack?

**Comment by sagarjumble** [comment]
I am using project from this link.
https://github.com/akveo/ng2-admin

**Comment by sagarjumble** [comment]
Is the above URL helpful.

**Comment by derekshi** [comment]
I have trouble get all the dependency installed because of the peerDependency incompatibility. Can you try resolve all the dependencies and try to use library with rc.6?

**Comment by derekshi** [comment]
Hi, I have added 'webpack demo' under `demo/webpack` folder. It may help you solve your problem.

**Comment by sagarjumble** [comment]
Still the same error.
zone.js:269 Uncaught Can't resolve all parameters for ToastContainer: (?, ToastOptions).

**Comment by jadav1982** [comment]
@sagarjumble , I am also getting same error. still you getting error?

**Comment by sagarjumble** [comment]
Yes I am still getting this error.

**Comment by derekshi** [comment]
I think the issue is in rc.6, Angular team renamed DomSanitizer. So make sure your angular 2 version is rc.6, not rc.5. Please let me know if upgrading to rc.6 solves your problem.

**Comment by derekshi** [comment]
@sagarjumble , @jadav1982 , either of you still get the error after upgrade? ng2-toastr v1.0.0 just released for official angular 2.0.0.

**Comment by taylorsmithgg** [comment]
![screen shot 2016-09-15 at 10 24 36 pm](https://cloud.githubusercontent.com/assets/6597925/18574494/3db24f92-7b93-11e6-9f98-48efaa0db6fa.png)

**Comment by taylorsmithgg** [comment]
CUSTOM_ELEMENTS_SCHEMA shows the toast, but the style doesn't work.

**Comment by derekshi** [comment]
You shouldn't add <toaster-container> in template. It will be dynamically created when needed.

**Comment by derekshi** [comment]
I am closing the issue assuming you have it fixed. Feel free to reopen it if necessary.
