### ISSUE TITLE
Not working with AOT compiler

### ISSUE THREAD

**Issue by ronzeidman** [PointInside/ng2-toastr#48]
I've been trying to AOT compile (ngc) while importing this module and I get a weird error:
```
Error: Unexpected value 'ToastModule' imported by the module 'ClientModule'
    at client\node_modules\@angular\compiler\bundles\compiler.umd.js:14118:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (client\node_modules\@angular\compiler\bundles\compiler.umd.js:14103:46)
    at client\node_modules\@angular\compiler\bundles\compiler.umd.js:12947:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (client\node_modules\@angular\compiler\bundles\compiler.umd.js:12946:21)
    at CodeGenerator.codegen (client\node_modules\@angular\compiler-cli\src\codegen.js:105:47)
    at codegen (client\node_modules\@angular\compiler-cli\src\main.js:7:81)
    at Object.main (client\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (client\node_modules\@angular\compiler-cli\src\main.js:14:9)
Compilation failed
```
I found this issue, maybe related: https://github.com/angular/angular/issues/11438
Although seems like the compilation of the module went fine... 
Not critical since AOT compilation is a new feature and probably has bugs so it maybe a bug in `@angular/compiler-cli` and not in your code (even though other modules work fine somehow...).

**Comment by derekshi** [comment]
I do find this an issue when you compile with ngc. Doing some research now.

**Comment by derekshi** [comment]
It seems like similar issue with: https://github.com/valor-software/ng2-bootstrap/issues/933. I guess I will fix it when angular 2 is official released.

**Comment by ronzeidman** [comment]
This thread seem to also contain the issue: https://github.com/angular/angular/issues/11262
Seems like you need to include `.metadata.json` files that are created by running `ngc` command on your repository

I've done it locally and it works, just `npm i -D @angular/compiler-cli @angular/platform-server`, add `"ngc", "ngc"` to the scripts and run npm run ngc and the metadata.json files will be generated

**Comment by derekshi** [comment]
@ronzeidman did you have issues when you using it?

**Comment by yuanfeiz** [comment]
@ronzeidman are you saying to compile the library or the application?

**Comment by ronzeidman** [comment]
@yuanfeiz compiling the library provides json files that help compile the application. My issue was about compiling the application and it should be resolved by compiling the library first.
@derekshi  I'll test if it works tomorrow (I hadn't got around it yet) and tell you if it resolved the issue for me.
Thanks

**Comment by derekshi** [comment]
@ronzeidman for the new releases, I have added metadata.json files, you should be able to compiling the application with the library. However, I haven't tested fully with an application built with ngc.

**Comment by ronzeidman** [comment]
Works great. Thanks
