### ISSUE TITLE
forRoot on ngModule

### ISSUE THREAD

**Issue by thaoula** [PointInside/ng2-toastr#49]
Hi Guys,

Since you are exposing a provider ToastsManager should you include a forRoot static method on the module to prevent ToastsManager from being created in lazy loaded modules.

https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root

Regards,
Tarek

**Comment by derekshi** [comment]
That's a good idea. I probably will look into this when angular 2 is official released.

**Comment by derekshi** [comment]
Added forRoot method on v1.0.1.
