### ISSUE TITLE
Cant compile when I include toastr

### ISSUE THREAD

**Issue by vovikdrg** [PointInside/ng2-toastr#5]
after i add 
import { ToastsManager } from 'ng2-toastr/ng2-toastr';
To my typescript it return error

error TS6059: File 'node_modules/ng2-toastr/ng2-toastr.ts' is not under 'rootDir' 'src'. 'rootDir' is expected to contain all source files.

**Comment by derekshi** [comment]
let me know if no solutions have been found yet.

**Comment by repkins** [comment]
I can recommend you to should separate typings ".d.ts" files from typescript source files in separate directories (currently they are in same directories) so tsc not compiles them in app when imports them. That should solve this issue.
