### ISSUE TITLE
.toast class in template

### ISSUE THREAD

**Issue by webmcheck** [PointInside/ng2-toastr#50]
I can't find class `.toast` in the template, and i have no idea how to override it.
![2016-09-14 12_11_33-ng2-toastr_toast-container component ts at master pointinside_ng2-toastr](https://cloud.githubusercontent.com/assets/1275723/18506523/1ddaacce-7a75-11e6-9d93-764c49b74437.png)

I think it's should be there because it exists in default CSS and in the original js-toastr

**Comment by derekshi** [comment]
All the css classes are defined in ng2-toastr.min.js file. You can attach your own css file to override any classes. Also check readme, you are able to override some of the classes in ToastOptions.

**Comment by webmcheck** [comment]
I mean `.toast` class used twice in `ng2-toastr.min.css`, but it never appears in generated HTML. 
It can be fixed on line 10, like so:
`<div *ngFor="let toast of toasts" class="toast toast-{{toast.type}}" (click)="dismiss(toast)">`

In options, we can configure only `title` and `message`, but not self toast class.

**Comment by derekshi** [comment]
Good catch. Updated template in v1.0.

**Comment by kobvel** [comment]
So, how can we override .toast message styles at the moment? I don't see updates in the doc @derekshi
