### ISSUE TITLE
Add support for toast close button (x).. 

### ISSUE THREAD

**Issue by narainsagar** [PointInside/ng2-toastr#51]
Hi, I just looked this  `ng2-toastr` lib - it is great, but as i saw the demo it isn't have close toast option button.. It would be great if you add support for close option (via [x] icon) on top right corner of toast or custom.. Thanks..

Here's snapshot for close toast icon:

![screen shot 2016-09-20 at 3 51 07 pm](https://cloud.githubusercontent.com/assets/13800762/18667493/3ec9c8a0-7f4a-11e6-9057-e3cc6116b28b.png)

Cheers,
Narain S.

**Comment by derekshi** [comment]
@narainsagar , we try to make this library as light and simple as possible. Although it doesn't have close button, you can achieve the same behavior by setting `autoDismiss: false`, which will enable click to dismiss behavior of the toast.

**Comment by narainsagar** [comment]
Huh, well as I think adding just a close button icon (x) and make it optional (like add option `showCloseButton: boolean` property will add a button with close icon(x) if **true**) won't make it complicated and high.. I think this is the only thing (feature) which is missing in this lib (from my point of view).. Anyways, That's Okay at all, Can you please tell me how can I re-generate bundles - i think you already had written code for it there: https://github.com/PointInside/ng2-toastr/blob/master/make.js but i am not able know how can i run/execute this.. any command or etc? or please just let me know about some dev guide to locally setup this repo i.e., DEVELOPER.md doc so i can extend this lib according to my need. Thanks.

**Comment by narainsagar** [comment]
^ I'll surely raise a PR once done..

**Comment by derekshi** [comment]
@narainsagar if you clone the repo, run `npm prepublish` you will rebuild all the files under `/bundles`.

**Comment by narainsagar** [comment]
@derekshi Ok cool.. 👍  Thanks..

**Comment by anvesh48** [comment]
@narainsagar @derekshi 
I know this issue is closed. But any update on this. As you guys discussed that you do a PR for adding the x icon to the toaster. I didn't see it in the documentation to how to use it?

**Comment by narainsagar** [comment]
@derekshi It's available in the latest release.

i.e., https://github.com/PointInside/ng2-toastr#whats-new
