### ISSUE TITLE
If I do not use systemjs, so how to use this library

### ISSUE THREAD

**Issue by dongtong** [PointInside/ng2-toastr#54]
Hi 

I checked the source code, I want to know, if I do not use systemjs, how to use it

**Comment by derekshi** [comment]
You can follow the demo/webpack example.

**Comment by njulhb** [comment]
Hi 

Is there any demo about browserify?

**Comment by derekshi** [comment]
Sorry, not at this moment. But you can follow the source in demo/webpack, and setup your browserify to load typescript (https://www.typescriptlang.org/docs/handbook/integrating-with-build-tools.html), you may able to make it work. Good luck.
