### ISSUE TITLE
TypeError: Cannot read property '_hostElement' of undefined

### ISSUE THREAD

**Issue by narainsagar** [PointInside/ng2-toastr#55]
Getting this error when calling from `app.component.ts`

I've provided `ToastsModule` into AppModule `imports` and called toast function in `ngAfterViewInit`.. 

```
export class AppComponent implements AfterViewInit{
  constructor(private toastr: ToastsManager) {}

  ngAfterViewInit() {
      this.toastr.success('Welcome.. Your App has been loaded..', 'Hello World', {autoDismiss: false});
  }
}
}
```

```
core.umd.js:3462 EXCEPTION: Error in http://localhost:4200/app/app.component.js class AppComponent_Host - inline template:0:0 caused by: Cannot read property '_hostElement' of undefined
```

I have logged `appRef` object it has 0 in _rootComponents.

The issue is probably on this [line](https://github.com/PointInside/ng2-toastr/blob/master/src/toast-manager.ts#L28)

Thanks...

**Comment by derekshi** [comment]
I think `ngAfterViewInit` happens earlier than angular sets up application reference component. That's why you get the error. Try this:
```
ngAfterViewInit () {
  setTimeout(() => {
        this.toastr.success('Welcome.. Your App has been loaded..', 'Hello World', {autoDismiss: false});
  }, 300);
}
```

**Comment by narainsagar** [comment]
Hi thanks.. Yes. Using this it's working.. but without using this i.e., `setTimeout` is there anyway we can achieve this?

Cheers,

**Comment by derekshi** [comment]
If you want to show toaster right after app is loaded, this may be the only way. Unless you can show toaster like the demo apps I included in the github.  I tested with setTimeout(..., 1), it also works (with 1 milisecond). I think Angular make sure setTimeout runs right after application has been fully loaded.

**Comment by narainsagar** [comment]
Ok, Cool.. +1
