### ISSUE TITLE
Uncaught TypeError: System.registerDynamic is not a function

### ISSUE THREAD

**Issue by bonaparte89** [PointInside/ng2-toastr#56]
Hello there,

i'm using the angular2-seed by mgechev. 
everything is working fine so far. but as soon as i "build.prod" which works and finishes.
So I load my final app and get the following error:

I'm not using webanimations.

`,System.registerDynamic("ng2-toastr/src/toast-container.component",["@angular/core","./toast-options","@angular/platform-browser"],!0,function(t,e,n){"use strict";var r=this,i=r.define;r.define=void 0;var o=t("@angular/core"),a=t("./toast-options"),s=t("@angular/platform-browser"),u=function(){function t(t,e){this.sanitizer=t,this.position="fixed",this.messageClass="toast-message",this.titleClass="toast-title",this.positionClass="toast-top-right",this.toasts=[],this.maxShown=5,this.animate="fade",e&&Object.assign(this,e)}return t.prototype.addToast=function(t){this.positionClass.indexOf("top")>0?(this.toasts.push(t),this.toasts.length>this.maxShown&&this.toasts.splice(0,this.toasts.length-this.maxShown)):(this.toasts.unshift(t),this.toasts.length>this.maxShown&&this.toasts.splice(this.maxShown,this.toasts.length-this.maxShown))},t.prototype.removeToast=function(t){this.toasts=this.toasts.filter(function(e){return e.id!==t})},t.prototype.removeAllToasts=function(){this.toasts=[]},t.prototype.dismiss=function(t){t.autoDismiss||this.removeToast(t.id)},t.prototype.anyToast=function(){return this.toasts.length>0},t.prototype.findToast=function(t){for(var e=0,n=this.toasts;e<n.length;e++){var r=n[e];if(r.id===t)return r}return null},t.decorators=[{type:o.Component,args:[{selector:"toast-container",template:'\n    <div id="toast-container" [style.position]="position" class="{{positionClass}}">\n      <div *ngFor="let toast of toasts" [@inOut]="animate" class="toast toast-{{toast.type}}" (click)="dismiss(toast)">\n        <div *ngIf="toast.title" class="{{toast.titleClass || titleClass}}">{{toast.title}}</div>\n        <div [ngSwitch]="toast.enableHTML">\n          <span *ngSwitchCase="true" [innerHTML]="sanitizer.bypassSecurityTrustHtml(toast.message)"></span>\n          <span *ngSwitchDefault class="{{toast.messageClass || messageClass}}">{{toast.message}}</span>\n        </div>              \n      </div>\n    </div>\n    ',animations:[o.trigger("inOut",[o.state("flyRight, flyLeft",o.style({opacity:1,transform:"translateX(0)"})),o.state("fade",o.style({opacity:1})),o.state("slideDown, slideUp",o.style({opacity:1,transform:"translateY(0)"})),o.transition("void => flyRight",[o.style({opacity:0,transform:"translateX(100%)"}),o.animate("0.2s ease-in")]),o.transition("flyRight => void",[o.animate("0.2s 10 ease-out",o.style({opacity:0,transform:"translateX(100%)"}))]),o.transition("void => flyLeft",[o.style({opacity:0,transform:"translateX(-100%)"}),o.animate("0.2s ease-in")]),o.transition("flyLeft => void",[o.animate("0.2s 10 ease-out",o.style({opacity:0,transform:"translateX(-100%)"}))]),o.transition("void => fade",[o.style({opacity:0}),o.animate("0.3s ease-in")]),o.transition("fade => void",[o.animate("0.3s 10 ease-out",o.style({opacity:0}))]),o.transition("void => slideDown",[o.style({opacity:0,transform:"translateY(-200%)"}),o.animate("0.3s ease-in")]),o.transition("slideDown => void",[o.animate("0.3s 10 ease-out",o.style({opacity:0,transform:"translateY(-200%)"}))]),o.transition("void => slideUp",[o.style({opacity:0,transform:"translateY(200%)"}),o.animate("0.3s ease-in")]),o.transition("slideUp => void",[o.animate("0.3s 10 ease-out",o.style({opacity:0,transform:"translateY(200%)"}))])])]}]}],t.ctorParameters=[{type:s.DomSanitizer},{type:a.ToastOptions,decorators:[{type:o.Optional}]}],t}();return e.ToastContainer=u,r.define=i,n.exports}),System.registerDynamic("ng2-toastr/src/toast",[],!0,function(t,e,n){"use strict";var r=this,i=r.define;r.define=void 0;var o=function(){function t(t,e,n){this.type=t,this.message=e,this.title=n,this.autoDismiss=!0,this.enableHTML=!1}return t}();return e.Toast=o,r.define=i,n.exports}),System.registerDynamic("ng2-toastr/src/toast-manager",["@angular/core","./toast-container.component","./toast-options","./toast"],!0,function(t,e,n){"use strict";var r=this,i=r.define;r.define=void 0;var o=t("@angular/core"),a=t("./toast-container.component"),s=t("./toast-options"),u=t("./toast"),c=function(){function t(t,e,n){this.componentFactoryResolver=t,this.appRef=e,this.options={autoDismiss:!0,toastLife:3e3},this.index=0,n&&Object.assign(this.options,n)}return t.prototype.show=function(t,e){if(this.container)this.setupToast(t,e);else{if(!this.appRef._rootComponents.length)return void console.error("Application root component cannot be found. Try accessing application reference in the later life cycle of angular app.");var n=this.appRef._rootComponents[0]._hostElement.vcRef,r=o.ReflectiveInjector.resolve([{provide:s.ToastOptions,useValue:this.options}]),i=this.componentFactoryResolver.resolveComponentFactory(a.ToastContainer),u=o.ReflectiveInjector.fromResolvedProviders(r,n.parentInjector);this.container=n.createComponent(i,n.length,u),this.setupToast(t,e)}},t.prototype.createTimeout=function(t,e){var n=this,r=e||this.options.toastLife;setTimeout(function(){n.clearToast(t)},r)},t.prototype.setupToast=function(t,e){t.id=++this.index,e&&"string"==typeof e.messageClass&&(t.messageClass=e.messageClass),e&&"string"==typeof e.titleClass&&(t.titleClass=e.titleClass),e&&"boolean"==typeof e.enableHTML&&(t.enableHTML=e.enableHTML),e&&"boolean"==typeof e.autoDismiss?t.autoDismiss=e.autoDismiss:t.autoDismiss=this.options.autoDismiss,e&&"number"==typeof e.toastLife?(t.autoDismiss=!0,this.createTimeout(t.id,e.toastLife)):t.autoDismiss&&this.createTimeout(t.id),this.container.instance.addToast(t)},t.prototype.clearToast=function(t){if(this.container){var e=this.container.instance;e.removeToast(t),e.anyToast()||this.dispose()}},t.prototype.clearAllToasts=function(){if(this.container){var t=this.container.instance;t.removeAllToasts(),t.anyToast()||this.dispose()}},t.prototype.dispose=function(){this.container.destroy(),this.container=null},t.prototype.error=function(t,e,n){var r=new u.Toast("error",t,e);this.show(r,n)},t.prototype.info=function(t,e,n){var r=new u.Toast("info",t,e);this.show(r,n)},t.prototype.success=function(t,e,n){var r=new u.Toast("success",t,e);this.show(r,n)},t.prototype.warning=function(t,e,n){var r=new u.Toast("warning",t,e);this.show(r,n)},t.prototype.custom=function(t,e,n){var r=new u.Toast("custom",t,e);this.show(r,n)},t.decorators=[{type:o.Injectable}],t.ctorParameters=[{type:o.ComponentFactoryResolver},{type:o.ApplicationRef},{type:s.ToastOptions,decorators:[{type:o.Optional}]}],t}();return e.ToastsManager=c,r.define=i,n.exports}),System.registerDynamic("ng2-toastr/src/toast-options",["@angular/core"],!0,function(t,e,n){"use strict";var r=this,i=r.define;r.define=void 0;var o=t("@angular/core"),a=function(){function t(t){this.enableHTML=!1,this.animate="fade",Object.assign(this,t)}return t.decorators=[{type:o.Injectable}],t.ctorParameters=[{type:Object}],t}();return e.ToastOptions=a,r.define=i,n.exports}),System.registerDynamic("ng2-toastr/src/toast.module",["@angular/core","@angular/common","./toast-container.component","./toast-manager","./toast-options"],!0,function(t,e,n){"use strict";var r=this,i=r.define;r.define=void 0;var o=t("@angular/core"),a=t("@angular/common"),s=t("./toast-container.component"),u=t("./toast-manager"),c=t("./toast-options"),l=function(){function t(){}return t.forRoot=function(e){return{ngModule:t,providers:[{provide:c.ToastOptions,useValue:e}]}},t.decorators=[{type:o.NgModule,args:[{imports:[a.CommonModule],declarations:[s.ToastContainer],exports:[s.ToastContainer],providers:[u.ToastsManager],entryComponents:[s.ToastContainer]}]}],t.ctorParameters=[],t}();return e.ToastModule=l,r.define=i,n.exports}),System.registerDynamic("ng2-toastr/ng2-toastr",["./src/toast","./src/toast-manager","./src/toast-container.component","./src/toast-options","./src/toast.module"],!0,function(t,e,n){"use strict";function r(t){for(var n in t)e.hasOwnProperty(n)||(e[n]=t[n])}var i=this,o=i.define;return i.define=void 0,r(t("./src/toast")),r(t("./src/toast-manager")),r(t("./src/toast-container.component")),r(t("./src/toast-options")),r(t("./src/toast.module")),i.define=o,n.exports`

any ideas on this one?

**Comment by derekshi** [comment]
I never used angular2-seed but I think the error generates because you tried to build ts files with bundled ng2-toastr.js. You can: 1) try exclude all the ng2-toastr bundled folder when building or 2) you can build all ng2-toastr source ts files together with your own app ts files, this way you don't have to include ng2-toastr.js on your html.

**Comment by lmkerr** [comment]
@bonaparte89 im coming across this issue now, with the same ng2-seed. which of his options did you end up doing to resolve this?

**Comment by derekshi** [comment]
If you build using `webpack`, please DON'T include `ng2-toastr.min.js` on your view header.

**Comment by bonaparte89** [comment]
- add the ng2-toastr.css to your npm dependencies (project conf)
- add the path to your system builder config (
'ng2-toastr':                     'node_modules/ng2-toastr', (path)
'ng2-toastr':                  { main: 'ng2-toastr.js', defaultExtension: 'js'}, (packages)

this worked for me :-)
