### ISSUE TITLE
Cannot use this in custom ErrorHandler subclass

### ISSUE THREAD

**Issue by xaralis** [PointInside/ng2-toastr#59]
I'm having issues when trying to use this in custom `ErrorHandler` for angular2. Is there some way to work around this error?

```
Uncaught Error: Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef_: in NgModule AppModule
```

My error handler looks like this:

```typescript
@Injectable()
export class AppErrorHandler extends ErrorHandler {
    constructor(private toastr: ToastsManager) {
        super(false);
    }
    handleError(err) {
        this.toastr.error(err.message);
        super.handleError(err);
    }
}
```

I'm registering my own error handler like this:

```typescript
@NgModule({
    ...
    providers: [
        {
            provide: ErrorHandler,
            useClass: AppErrorHandler,
        },
    ],
    ...
})
```

**Comment by mvareeth** [comment]
When I use this custom ErrorHandler, I got this issue
Uncaught TypeError: Cannot read property '_rootComponents' of undefined

**Comment by xaralis** [comment]
@mvareeth Yeah, I was getting this sometimes too when I played with it. But it's still coming from `ng2-toastr` internals.

**Comment by derekshi** [comment]
This happens because the root ApplicationRef has not been initialized when angular loads ErrorHandler. Can you tell me when you get this error, when an error happens or when the application gets initiated? How do you use ErrorHandler? You may need to refer to `forwardRef` (https://angular.io/docs/ts/latest/api/core/index/forwardRef-function.html)

**Comment by derekshi** [comment]
I updated dev branch to use `forwardRef(() => ApplicationRef)`. See if it resolves your problem. When referring dev branch, update your package.json:
`"ng2-toastr": "PointInside/ng2-toastr#dev"`

**Comment by derekshi** [comment]
@mvareeth, you probably calling `toastr.success` or any other 'show' methods too early in the application cycle. Trying wrap the function with setTimeout, such as
```
 setTimeout(() => {
   this.toastr.success(....);
 }, 10);
```

**Comment by derekshi** [comment]
@xaralis Ok, I tested with your `ErrorHandler` and only way I made it work is set ErrorHandler provider at your root component, not in the ngModule.

**Comment by xaralis** [comment]
@derekshi Thanks for investigating. While defining ErrorHandler on root component level feels a bit dirty, it's acceptable solution for now I think.

**Comment by derekshi** [comment]
I agree. I wonder that's something angular 2 team is solving. I tried using `forwardRef`, but doesn't seem to work.

**Comment by xaralis** [comment]
@derekshi I've just tried to do it the way you suggest but it seems my component providers are not being taken into account.

I took it out from module definition and defined it under my root component:

```typescript
@Component({
    selector: 'app',
    templateUrl: 'app.component.html',
    styleUrls: ['app.component.less'],
    providers: [
        {
            provide: ErrorHandler,
            useClass: AppErrorHandler,
        }
    ]
})
export class AppComponent implements OnInit {...}
```

Well, it turns out it doesn't have any effect this way, my ```AppErrorHandler``` is not used at all.

**Comment by xaralis** [comment]
For the record, i was able to solve this using following code:

```typescript
import {ErrorHandler, Injectable, Injector} from '@angular/core';
import {ToastsManager} from 'ng2-toastr/ng2-toastr';

@Injectable()
export class AppErrorHandler extends ErrorHandler {
    constructor(private injector: Injector) {
        super();
    }

    handleError(err) {
        let toastr = <ToastsManager>this.injector.get(ToastsManager);

        setTimeout(() => {
            toastr.error('Error', null, {autoDismiss: false});
        });

        super.handleError(err);

    }
}
```

I think that is the only option currently when ng2-toastr needs to touch `ApplicationRef`. As it doesn't feel that ugly, I'm closing this issue.

**Comment by derekshi** [comment]
@xaralis Thanks. Glad you find an elegant solution.

**Comment by AlexOg37** [comment]
hi @derekshi , you mentioned above that angular 2 team is solving this issue. do you have any link to this issue in ng2 repo? thnx

**Comment by gandarez** [comment]
Already having this issue using angular 4.4.6, ng2-toastr 4.1.2
