### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by rkrayovskyy** [PointInside/ng2-toastr#6]
Hi,

seems like to make it work you need to declare constructor in the following way:
```
constructor(toastr: ToastsManager) {
  this.toastr = toastr; // add this line
}
```

thanks for this plugin, looks great so far :)
Roman

**Comment by derekshi** [comment]
Hi, in typescript, if you put `public` or `private` modifier in front of params in constructor like this:
```
constructor(public toastr: ToastsManager) { }
```
It would automatically create `this.toastr` for you.
