### ISSUE TITLE
Wouldn't it be good to be able to click-dismiss AND auto dismiss?

### ISSUE THREAD

**Issue by janneromell** [PointInside/ng2-toastr#61]
Normally you want a toast to auto dismiss after some given time. But you ALSO want a close button (a cross icon) in the upper right to dismiss the toast premature of the auto-dismiss timeout. Most toasts works like that.

**Comment by derekshi** [comment]
We could. The reason we omit close button is sometimes 'x' button is too small for finger to press when you are viewing on mobile screen. You can simply set `dismiss: 'click'` and the whole toast will be click-to-dismiss when user clicks anywhere on toast.

**Comment by janneromell** [comment]
Well, the dismiss: 'click' option as a few problems:
* No affordance for the end user that the toast can be dismissed
* A click on the whole toast usually means a navigation or and action to do something
* If you set dismiss: click, you cannot have a time based autodismiss. 

I suggest (and I know I should probably contribute instead, see when I can find the time):
* An 'x' button that is different in layout (CSS) by media queries, thus bigger on small screens/touch.
* Always shown an 'x' button IF the toast is dismissable
* Combine click and autoDismiss, so that you can have the toast autoDismiss, but the user can prematurely dismiss it. (I think this is de facto behavior for toasts)

**Comment by derekshi** [comment]
@janneromell , you made some points there. We will think about the best way to implement it in later releases.

**Comment by anvesh48** [comment]
@derekshi Any update on tapOnDismiss option? As it is so important for our project to get up and running.

**Comment by derekshi** [comment]
@anvesh48 you can set `{dismiss: 'click'}` to tap on dismiss. For the close button, we haven't got to that yet.

**Comment by anvesh48** [comment]
@derekshi Thanks for taking your time to reply back. Derekshi, we would like to have both dismiss: click and toastLife: 4000 in place for our project. In simple words, our user should be able to close the toaster at any time by clicking  on the x icon or else, he can wait until 4 secs to pass to get the toaster dismissed. tapOnDismiss was used to be the property that makes us to work. Also, any plans on adding 'x' icon for the toaster please.

**Comment by derekshi** [comment]
@anvesh48 , those features are not implemented yet. But feel free to add those and send us pull request. We want to add `click` and `hover` events handler to toasts first, which can enable lots of possibilities while keep the library lightweight.

**Comment by derekshi** [comment]
@janneromell , on version 1.3.0, you have `showCloseButton` option and you can also subscribe to `toastsmanager.onClickToast()` observable to handle logic when toast is clicked.

**Comment by janneromell** [comment]
showCloseButton works perfect. 

The only thing I didn't get to work, was to set the "global config" of toasts to use showCloseButton, like this:

let toastConfig: any = {
    animate: "flyRight",
    positionClass: "toast-bottom-right",
    showCloseButton : true   <-------
};

    imports: [
        ...
        ToastModule.forRoot(toastConfig),
        ...
    ]

I instead had to send it with every call:

        let options: ToastOptions = new ToastOptions({});
        options.showCloseButton = true;
        this.toasterService.error(message, pm.title, options);

But maybe that is by design?

**Comment by derekshi** [comment]
Mmm, it should work though because I tested on the demo app. Did you override ToastOptions somewhere else?

**Comment by jaklithn** [comment]
timeOutand tapToDismiss would be lovely to combine!
In my mind that is the natural choice that I always use.
To show a closeButton is a nice option for visibility that I use most of the time as well.

Currently I reference the original toastr lib to ensure full user experience, but I would really like to avoid jQuery reference ...

**Comment by TomJahncke** [comment]
I fully agree that "timeOut and tapToDismiss would be lovely to combine!"  In fact, without this feature I probably won't be able to use this library.  It seems that tapToDimiss and timeOut working together are normal behavior for a toastr library, based on looking at http://codeseven.github.io/toastr/demo.html

Is this a feature that is being considered?  (If not that is okay, I just would like to know so I can plan what toastr library to use with my angular 2 application.)

**Comment by derekshi** [comment]
This is available. You can use combination of `dismiss: 'auto', showCloseButton: true`. You can also programmatically control the dismiss when user click anywhere on toast.

**Comment by TomJahncke** [comment]
I was aware of the showCloseButton option.  However, this is being used on a mobile device and clicking the X is too precise of an operator for what I am looking for.   Would you be able to provide an example as to how to programmatically control the dismiss when the user clicks anywhere on the toast?

**Comment by derekshi** [comment]
@TomJahncke In you case, you should subscribe to `Toastsmanager.onClickToast()` Observable, and dismiss the toast and clear the timer programmatically.

**Comment by derekshi** [comment]
@TomJahncke some sample code you can use:
```
 this.toastr.onClickToast()
    .subscribe( toast => {            
        if (toast.timeoutId) {
          clearTimeout(toast.timeoutId);
        }
        this.toastr.dismiss(toast);  
    });
```

**Comment by iDGE90** [comment]
> this.toastr.dismiss(toast);

`to`

this.toastr.dismissToast(toast);
