### ISSUE TITLE
Why can not override animate and positionClass?

### ISSUE THREAD

**Issue by dongtong** [PointInside/ng2-toastr#63]
Hey

Why can not override animate and positionClass?

**Comment by derekshi** [comment]
Good question. The way we first designed is for super lightweight and maintain only one container throughout the app. This should meet majority of cases when user interface wants to be consistent and predictable. Can you make a good case when you want to change position and animate for certain toasts? We may able to add these features to future releases.

**Comment by derekshi** [comment]
Closing this issue for now. We might add these features later on.
