### ISSUE TITLE
Previous toast isn't disposed

### ISSUE THREAD

**Issue by antonkallenberg** [PointInside/ng2-toastr#69]
I've probably misunderstood something, but... 

By default previous toasts doesn't seems be disposed and removed so when I trigger a new toast the previous ones are shown as well, is this expected behavior or have I configured something wrong?

I've also tried to remove the Toast after it has been triggered, something like:
``` typescript 
this.toastr.success(message, title, options).then((toast: Toast) => {
    setTimeout(() => {
        this.toastr.dismissToast(toast);
        this.toastr.clearToast(toast.id);
    }, this.killTime);                    
});  
```
but the toast isn't removed... can you please confirm this or explain what's going on?
Isn't it suppose to work like toastr (http://codeseven.github.io/toastr/demo.html)?
I'm using version 1.2.1

**Comment by derekshi** [comment]
You need to set `{dismiss: 'controlled'}` if you want to dismiss the toast yourself. See example in readme.

**Comment by antonkallenberg** [comment]
@derekshi That works great, thanks for bringing us ng2-toastr!
