### ISSUE TITLE
Return toast id

### ISSUE THREAD

**Issue by pallmallshow** [PointInside/ng2-toastr#7]
Hi,

First, thank for your package. It is very usefull :)

But, I need to display two consecutive toastr, but the last one, remove the first.
A method `clearToast` is available, but it takes the toast id on first arg.
We havn't this toastId.

So, it would be cool, to return toast object, or just the toast id, every time we create a new toast.

Thanks !

**Comment by derekshi** [comment]
If you just want to display one message at a time, you can set ToastOptions({maxShown: 1}).

**Comment by derekshi** [comment]
@pallmallshow FYI. Since ng2-toastr v1.2.0, all 'show' methods return `Promise<Toast>`. Now you can have your own logic when to dismiss the toast.
