### ISSUE TITLE
toast.config.ts setup in angular2

### ISSUE THREAD

**Issue by anvesh48** [PointInside/ng2-toastr#70]
There is an example that is there in our documentation, for configuring a toaster in app.module.ts by using let options: any = { }, I appreciate the work you put there in the example. Also i see that the ToastOptions has not been used anywhere. I am looking to move the code for configuration into a separate file like toaster.config.ts. Can you please provide me an example if you have some free time.

**Comment by derekshi** [comment]
You can use it this way:
```
export declare var myConfig : ToastOptions = new ToastOptions({ toastLife: 3000});
```

Then you can simply import `myConfig` in your xxx.module.ts.
