### ISSUE TITLE
dismiss: controlled -> on click?

### ISSUE THREAD

**Issue by Celaniry** [PointInside/ng2-toastr#71]
Is there any way to use the dismiss: 'controlled' option and still be able to close the same toast with an click? My idea was to run another function after closing the toast by click...

**Comment by derekshi** [comment]
Good point. We will have that on next lease.

**Comment by derekshi** [comment]
@Celaniry on version 1.3.0. you can use `showCloseButton: true` or you can subscribe to `toastsManager.onClickToast()` observable to implement your own logic.

**Comment by Celaniry** [comment]
Awesome. Thanks alot. Really appreciate your work!
