### ISSUE TITLE
Issue: Failed to parse SourceMap

### ISSUE THREAD

**Issue by anarvaez292** [PointInside/ng2-toastr#72]
The plugin works however, in the browser I'm getting the following error:

Failed to parse SourceMap: http://localhost:4000/node_modules/ng2-toastr/src/toast.js.map
Failed to parse SourceMap: http://localhost:4000/node_modules/ng2-toastr/src/toast-manager.js.map
Failed to parse SourceMap: http://localhost:4000/node_modules/ng2-toastr/src/toast-container.component.js.map
Failed to parse SourceMap: http://localhost:4000/node_modules/ng2-toastr/src/toast-options.js.map
Failed to parse SourceMap: http://localhost:4000/node_modules/ng2-toastr/src/toast.module.js.map

**Comment by IlyaSurmay** [comment]
I also have similar issue
Cannot find SourceMap 'ng2-toastr.js.map': Error: Cannot resolve 'file' or 'directory' ./ng2-toastr.js.map in project/node_modules/ng2-toastr

**Comment by derekshi** [comment]
Close for now. recommend `angular-cli` or `webpack` to build the project.
