### ISSUE TITLE
Add dynamic text

### ISSUE THREAD

**Issue by SimonaMilchevska** [PointInside/ng2-toastr#73]
I want to do something like this: 
showCustom() {
        this.toastr.custom('<span style="color: red">{{ document.name  }}</span>', null, {enableHTML: true});
      }
But it is  not showing the value of the document, it shows this part "{{ document.name  }}" as string. I expected that it shows the document name.

Or otherways asked, is it possible to use two-way data binding on this place?

**Comment by derekshi** [comment]
You should be able to accomplish this using sting interpolation.

**Comment by SimonaMilchevska** [comment]
Do you mean something like this: 
this.toastr.custom('<span class="toast-custom-copy toast-custom"> {{ toastMsg}} </span>', null, {enableHTML: true, toastLife: 700});

**Comment by SimonaMilchevska** [comment]
this.toastr.custom('<span class="toast-custom-copy toast-custom"> {{ toastMsg}} </span>', null, {enableHTML: true, toastLife: 700});

**Comment by GaryB432** [comment]
He means string interpolation like this

```
showCustom() {
        this.toastr.custom(`<span style="color: red">${document.name}</span>`, null, {enableHTML: true});
      }
```

**Comment by derekshi** [comment]
what's `document.name`? is it not from the ng2 component?

**Comment by SimonaMilchevska** [comment]
document.name  is dynamic variable

**Comment by SimonaMilchevska** [comment]
` this.toastr.custom('<span class="toast-custom-copy toast-custom"> '+ this.document.anme + ' </span>', null, {enableHTML: true, toastLife: 700});`

this is working

**Comment by derekshi** [comment]
you can also do: `<span class="toast-custom-copy toast-custom">${this.document.name} </span>`
