### ISSUE TITLE
Is it possible to customize the background color of a toast?

### ISSUE THREAD

**Issue by ryu323** [PointInside/ng2-toastr#74]
Thanks in advance.

**Comment by derekshi** [comment]
You can always provide your own css to replace classes defined in `ng2-toaster.css` . Or you can use `toastr.custom` and `enableHTML: true` combination to provide any styling yourself.

**Comment by derekshi** [comment]
@ryu323 you are right. Just add:
```
.toast-custom {
  background-color: #any_color_you_like;
}
```
And use `toastr.custom` should do it.

**Comment by ryu323** [comment]
thanks.

**Comment by pacurtin** [comment]
Does this work? I just get the following:
![screen shot 2017-11-16 at 12 36 01 pm](https://user-images.githubusercontent.com/17761806/32871098-d955809a-caca-11e7-9ecb-27c9565420ea.png)

`this.toastr.custom('<p class="toast-custom">"You are awesome!"</p>', 'Success!', {enableHTML: true})`

`.toast-custom {
  background-color: #any_color_you_like;
}`

Am I missing something here? It seem to me that this API only exposes the title and message for customisation. I cant figure out a way to customise the actual card. I want to change the colors to match my apps theme. I also want to change the cards z-index value to have toasts appear in front of a floating tool bar.

**Comment by pacurtin** [comment]
For anyone else who faces this. I found my problem. 

'      "styles": [
        "../node_modules/ng2-toastr/bundles/ng2-toastr.min.css",
        "styles.scss"
      ],'

In angular-cli.json make sure your custom css is AFTER "../node_modules/ng2-toastr/bundles/ng2-toastr.min.css" so it will succesfully overwrite.

**Comment by pacurtin** [comment]
Then you don't even need {enableHTML: true}
