### ISSUE TITLE
ToastModule not exported - Bundle failed with Angular2-AoT / RollUp / Ionic2

### ISSUE THREAD

**Issue by NightkingCH** [PointInside/ng2-toastr#75]
Hi there.

I'm facing a problem when using your module with Ionic2. Everything works fine until rollup / the bundle-task kicks in and tries to resolve the ToastModule. It reports following error:

` bundle failed: 'ToastModule' is not exported by node_modules\ng2-toastr\ng2-toastr.js (imported
            by .tmp\app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module`

If I do the same with a non ionic2 app it gives me following error: 

**Remark: I didn't imported the 'ToastModule' to check if it is just a single file!**

`'ToastsManager' is not exported by node_modules\ng2-toastr\ng2-toastr.js (imported by aot\app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module`

**What does my code look like?**

I made a minimalistic plunkr setup. Just download the zip and do the following steps:

1. npm install
2. npm run aot
3. ```'ToastModule' is not exported by node_modules\ng2-toastr\ng2-toastr.js (imported by aot\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module```

**Plunkr sample**

http://plnkr.co/edit/kjVLywf6sV1Qfh4LFrYc?p=info

Could someone guide me or provide a proper solution? Is this a problem with your module or did I made a mistake?

My workaround for now is to fork the code into my project, but this can't be a solution :).

**Comment by derekshi** [comment]
@NightkingCH , we haven't worked on Rollup/Ionic2, would you please suggest the fix since you have already fork the library and found a solution? Feel free to send us a pull request though.

**Comment by derekshi** [comment]
Please re-open this issue if needed.

**Comment by NightkingCH** [comment]
The final solution was to tell rollup that some classes are not directly exported like:

```
var toastModule_1 = require('./src/toast.module');
exports.ToastModule = toastModule;
```

but rather exported like that:

```__export(require('./src/toast.module'));```
`
So rollup doesn't know where it has to look for.

The rollup config for this case has to be like this:

```
import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify';

var options = {
    entry: './aot/tmp/app/main.aot.js',
    dest: './wwwroot/app/build.js', // output a single application bundle
    sourceMap: true,
    format: 'iife',
    treeshake: true,
    moduleName: "app",
    indent: false,
    plugins: [
        nodeResolve({
            jsnext: true, module: true
        }),
        commonjs({
            include: 'node_modules/**',
            namedExports: {
                'node_modules/ng2-toastr/ng2-toastr.js': [ 'ToastModule', 'ToastsManager' ],
                'node_modules/ng2-bs3-modal/ng2-bs3-modal.js': [ 'ModalComponent' ]
            }
        })
    ]
};

export default options;
```

Took a couple days to figure this out, sorry for my late response.

**Comment by Rob-Post** [comment]
@NightkingCH 

I tried your solution by adding 
```
namedExports: {
	'node_modules/ng2-toastr/ng2-toastr.js': [ 'ToastModule', 'ToastsManager' ]
}
```
to rollup-config, however I still get the same error. Did you change anything else?

**Comment by NightkingCH** [comment]
@Rob-Post 

Unfortunately I didn't. My main solution was to change the include to not list every module but rather let rollup traverse the node_modules directory. And after this I just added the "namedExports" part.

When I listed every module I just had more troubles. 

I`m sorry for not having a proper solution / answer.

**Comment by Rob-Post** [comment]
@NightkingCH 

Is it an option to reopen this issue so the developers can look into it?
