### ISSUE TITLE
Toaster loaded inside sibling app element

### ISSUE THREAD

**Issue by AlmogShaul** [PointInside/ng2-toastr#76]
When there is a sibling element :
    <body>
      <app></app>
      <sibling-element></sibling-element>
    </body>
and I try to open a toaster with toasterManager.error(.....)
The toaster element will be inside the sibling-element instead of being near the app element on the same level.
I think the problem is in line 50 in the toaster-manager class

        this.container = appContainer.createComponent(toastFactory, appContainer.length, childInjector);

appContainer.length is 1 in the case above so instead of creating the component inside the app element in index 0 it creates it in the sibling in index 1

That cause a big problem when I remove the sibling element , the toaster will be removed also and wil never go back again

**Comment by derekshi** [comment]
@AlmogShaul toaster should be created as a sibling element of your angular app. If `<app></app>` is your angular 2 app, a `<toaster-container>...</toaster-container>` will be created as next sibling element of `<app>`. It shouldn't matter whether you have other sibling elements or not. The only thing you have to make sure the `z-index` of your other sibling elements should not be higher than that of toaster container, which I believe is set to 99999.

**Comment by AlmogShaul** [comment]
You are right in your assumption, but in reality it is not work as expected (when there is sibling element)

**Comment by derekshi** [comment]
Can you show me some of the code? I added a sibling element to the demo app, it works as expected.

**Comment by AlmogShaul** [comment]
Checked it again,It is not the toaster problem...
