### ISSUE TITLE
All Options are required

### ISSUE THREAD

**Issue by digital216** [PointInside/ng2-toastr#77]
If I attempt to override one option:

    ToastModule.forRoot({
        positionClass: "toast-top-full-width"
    }

I get a Typescript compile error that I am missing the `maxShown` option.  If I fill that in (even with the default value) I get another error message for `newestOnTop`...and so on through all the properties.  Can the ToastOptions options be made optional (wow, that's a lot of "option" terms) so you can only override the ones you want and not have to specify them all?

I've worked around this by just adding the "optional" (`?`) operator to each property (`positionClass?: string`) in the definition file, but I'm not sure if that's a valid method of fixing this.

**Comment by derekshi** [comment]
You need to do this way:
```
let options = new ToastOptions({
  positionClass: "toast-top-full-width"
});

ToastModule.forRoot(options) ...
```

**Comment by digital216** [comment]
Awesome, with that being the case, all we should need is the documentation updated (since it only mentions doing it with an `any` type object).

Thanks for pointing out the right way to do it!!
