### ISSUE TITLE
Styles aren't applied?

### ISSUE THREAD

**Issue by georgeedwards** [PointInside/ng2-toastr#81]
I am trying to add this to an angular 2.1.2 based app, using webpack2. 

I have added:

```
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
<script src="http://hammerjs.github.io/dist/hammer.min.js"></script>
<script src="http://cdn.rawgit.com/hammerjs/touchemulator/master/touch-emulator.js"></script>
```

to my index.html

and then copied the component and html exactly from the demo. However, I just get the toasts without any styling. e.g.
[![enter image description here][1]][1]

I even tried adding 

```
#toast-container {
    background-color: lightgrey;
    padding: 20px;
    border-radius: 5px;
    margin-left: 20px;
    margin-right: 20px;
}
```
to my `notifications.component.css` file, but it didn't work. The css in that file is working, as I added a `color: green` to h1's which you can see from the image above is working. 

I can't see any of the styles in the Google Chrome Inspector (not even crossed/greyed out)

Am I doing something wrong, or is this a bug?

  [1]: https://i.stack.imgur.com/fjYb6.png

**Comment by anarvaez292** [comment]
I believe I was having the same issue.  I explicitly imported the css file in node_modules/ng2-toastr and it worked.

**Comment by derekshi** [comment]
did you add 
```<link href="node_modules/ng2-toastr/bundles/ng2-toastr.min.css" rel="stylesheet" />``` ?

**Comment by anarvaez292** [comment]
More or less. You could do that. I actually copied that css file and put it in my project and referenced it to that specific location.

**Comment by derekshi** [comment]
@anarvaez292 : did you mean even if you referenced css file and it still not working?

**Comment by anarvaez292** [comment]
Referencing by <link href="node_modules/ng2-toastr/bundles/ng2-toastr.min.css" rel="stylesheet" /> should work.

**Comment by georgeedwards** [comment]
I am not sure it's a referencing issue. If I copy the contents on `ng2-toastr.css` into my component.css file, I still don't get the stylings...

**Comment by derekshi** [comment]
@georgeedwards , you can use browser dev tools to see if the css file got loaded correctly. and you can also inspect the element to see if the right css class is applied to the element.
