### ISSUE TITLE
Issue with npm install ng2-toastr

### ISSUE THREAD

**Issue by jdiapps** [PointInside/ng2-toastr#82]
I get the following errors: Note I have angular 2.0.1 installed

+-- UNMET PEER DEPENDENCY @angular/common@2.0.1
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.1
+-- UNMET PEER DEPENDENCY @angular/core@2.0.1
+-- UNMET PEER DEPENDENCY @angular/forms@2.0.1

**Comment by derekshi** [comment]
@jdiapps : do you still have problem of installing? I believe it's not an issue for ng2-toastr.
