### ISSUE TITLE
How to use an Angular Material in custom toast?

### ISSUE THREAD

**Issue by georgeedwards** [PointInside/ng2-toastr#83]
I am hoping to include an angular material input in a custom toast, e.g. 

```
    showCustomHTML() {
        this.toastr.custom('<md-input placeholder="amount"></md-input><span style="color: #bd362f">This message should be in red with blank background. Click to dismiss.</span>',
            'Stop', { enableHTML: true, dismiss: 'click' });
    }
```
However, it does not display. This is presumably because the component which launches the notification (buried somewhere in the npm package) hasn't got Angular Material provided to it. 

How can I do this?

**Comment by derekshi** [comment]
I don't think this will work. `md-input` is a md directive, you need to find a way to make angular interpret it.

**Comment by georgeedwards** [comment]
What is the notification in angular though? Is is a component? If so, how can I provide something to it?

**Comment by derekshi** [comment]
The notification container as a whole is an angular component. But when you inject `html` into it, it will only interpret it as pure html.
