### ISSUE TITLE
Broken in Angular 2.2.0

### ISSUE THREAD

**Issue by tariknz** [PointInside/ng2-toastr#84]
Seems like you're accessing a private method to get the root app's ViewContainerRef. This must've been refactored in 2.2.0.

`toast-manager.ts:40`

**Comment by krocon** [comment]
Similar to this problem: https://github.com/angular/angular/issues/9293
and this: https://github.com/valor-software/ng2-bootstrap/issues/1235

**Comment by derekshi** [comment]
I had a temporary solution for Angular 2.2.0.  Please use ng2-toastr v1.3.1. In your root component of your app, do this:
```
   // AppComponent.ts (Root component of your app)

    constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
        this.toastr.setRootViewContainerRef(vRef);
    }
```

**Comment by tariknz** [comment]
That's actually a fair approach when considering dependency injection. Also I imagine it (although I'm not sure) you could make the toast appear relative to the current components view. 

Do you want me to close this for now or are you planning a long term solution?

**Comment by derekshi** [comment]
I think if you pass any current component's `ViewContainerRef` to ToastManager, you should get the toast appear relative to it.

**Comment by joshterrill** [comment]
Here's my solution:

```
import { Component, OnInit, ViewContainerRef, ApplicationRef } from '@angular/core';
constructor(private vcr : ViewContainerRef, private appRef : ApplicationRef) {}
this.appRef['_rootComponents'][0]['_hostElement'] = {};
this.appRef['_rootComponents'][0]['_hostElement']['vcRef'] = this.vcr;
```

**Comment by krocon** [comment]
thanks for your help! you can close it.

best regards
marc

Am 16.11.2016 23:13 schrieb "tariknz" <notifications@github.com>:
>
> That's actually a fair approach when considering dependency injection.
Also I imagine it (although I'm not sure) you could make the toast appear
relative to the current components view.
>
> Do you want me to close this for now or are you planning a long term
solution?
