### ISSUE TITLE
Load all Rxjs files

### ISSUE THREAD

**Issue by webmcheck** [PointInside/ng2-toastr#89]
I have problem with uploading all rxjs files (~300).
I think is happening because wrong import used here: https://github.com/PointInside/ng2-toastr/blob/master/src/toast-manager.ts#L8

Should be some like this:
import { Observable } from "rxjs/Observable";
import { Subject } from "rxjs/Subject";

Here is pull request. https://github.com/PointInside/ng2-toastr/pull/88

**Comment by derekshi** [comment]
@webmcheck I don't see the difference. `rxjs/Rx` imports both `Observable` and `Subject` from `rxjs/Observable` and `rxjs/Subject` respectively.

**Comment by webmcheck** [comment]
@derekshi yes you are right, but also rxjs/Rx imports all rxjs operators, about 130 files
