### ISSUE TITLE
package.json needs to be updated

### ISSUE THREAD

**Issue by jgr3go** [PointInside/ng2-toastr#9]
In package.json, `main` is set to an non-existent file

`"main": "index.js"`

If you instead set it to `ng2-toastr.js`, you wouldn't need to `import from ng2-toastr/ng2-toastr`, you could just `import from ng2-toastr`. 

Also, there is no `typings` key, which is how typescript determines the typings.  You should set this to your `.d.ts` file (see http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html)

**Comment by derekshi** [comment]
It's updated in v0.1.10.
