### ISSUE TITLE
Can not read property 'vcRef' of undefined

### ISSUE THREAD

**Issue by NShulzhenko** [PointInside/ng2-toastr#91]
![image](https://cloud.githubusercontent.com/assets/8741400/20434917/a900e87a-adb2-11e6-83fe-d783c7c7e6d9.png)

In show method I faced a problem finding hostElement (see at watcher). I think it is something due to version of angular2, I am using 2.1.2.

**Comment by NShulzhenko** [comment]
![image](https://cloud.githubusercontent.com/assets/8741400/20435512/1209fe86-adb5-11e6-9be5-644bcd49b71a.png)
It is working in angular 2.0.0 because of existing hostElement property.

Please fix it for a newest version of angular.

**Comment by NShulzhenko** [comment]
Solution was found in documentation. Thank you for updates.

**Comment by jim-finlon** [comment]
Where in the documentation? I am having the same issue
