### ISSUE TITLE
AoT compilation fails: ToastOptions is not exported

### ISSUE THREAD

**Issue by rkrayovskyy** [PointInside/ng2-toastr#92]
Hi,

the following error raises when trying to compile AoT bundle with Rollup:

> 'ToastOptions' is not exported by node_modules/ng2-toastr/ng2-toastr.js (imported by app/app.module.js).

Tried to fix by defining missing module but with no luck:
```
namedExports: {
                'node_modules/ng2-toastr/ng2-toastr.js': [ 'ToastOptions' ]
              }
```

Any hint?

**Comment by derekshi** [comment]
Close due to lack of details. Try the most recent version.
