### ISSUE TITLE
Angular no longer references rootViewContainerRef at _this.appRef['_rootComponents'][0]['_hostElement'].vcRef;

### ISSUE THREAD

**Issue by cwjolly** [PointInside/ng2-toastr#95]
in ToasterManager.js  show function  the code tries to obtain the rootViewContainerRef :
`   _this._rootViewContainerRef = _this.appRef['_rootComponents'][0]['_hostElement'].vcRef;`
but _this.appRef['_rootComponents'][0]['_hostElement'] is undefined  and no other child of _this.appRef['_rootComponents'][0] has a vcRef member. 

`Error: Uncaught (in promise): TypeError: Cannot read property 'vcRef' of undefined
TypeError: Cannot read property 'vcRef' of undefined
    at ToastsManager.show (http://localhost:8000/main.bundle.js:73106:101)
    at new ZoneAwarePromise (http://localhost:8000/main.bundle.js:119367:29)
    at ToastsManager.show (http://localhost:8000/main.bundle.js:73097:16)
    at ToastsManager.info (http://localhost:8000/main.bundle.js:73190:21)`

**Comment by derekshi** [comment]
Please read Readme for angular 2.2 fix.

**Comment by FabienDehopre** [comment]
I have the exact same issue. I followed the fix for the 2.2.x breaking change but I still have the issue.
For info, I use the ToastsManager in services, not in components (and some services are parts of module that are lazy loaded).
Does the fix provided in the readme works for this case or do I need to do the work around in service constructor?

**Comment by bravenewworlds** [comment]
The fix for the 2.2.x was not helped me too. I've tried on a simple helloworld-quickstart app from 
[https://github.com/angular/quickstart](url)

A toast was shown, but in the console got this:

> Error: Application root component cannot be found. Try accessing application reference in the later life cycle of angular app.

**Comment by derekshi** [comment]
@FabienDehopre, ToastsManager needs ViewContainerRef to display toasts on DOM. If you are using service, you need to make sure ToastsManager has access to ViewContainerRef somehow.

@bravenewworlds, you might be try to display toast too early in angular app cycle, maybe before application view is initialized.

**Comment by rodneyjoyce** [comment]
This fix worked for me, thanks

**Comment by AJRedDevil** [comment]
Thanks for the quick fix.
