### ISSUE TITLE
ToastOptions interface

### ISSUE THREAD

**Issue by tsm91** [PointInside/ng2-toastr#98]
If i want to override `toastLife` to be 5sec i have to specify all other Toast config options otherwise TS will cry. The ToastOptions interface facing to user should be all optional. You probably do something like `Object.assign({, defaultOpts, opts})` internally anyways.

```ts
export declare class ToastOptions {
    positionClass: string;
    maxShown: number;
    newestOnTop: boolean;
    animate: string;
    toastLife: number;
    enableHTML: boolean;
    dismiss: 'auto' | 'click' | 'controlled';
    messageClass: string;
    titleClass: string;
    showCloseButton: boolean;
    constructor(options: Object);
}
```

**Comment by derekshi** [comment]
why not do this:
```
let options = new ToastOptions({
  toastLife: 5000,
})
```

**Comment by tsm91** [comment]
ahh lol, sorry

it is even in the docs I just didn't fully read it
