### ISSUE TITLE
How to use ToastMangaer inside  services?

### ISSUE THREAD

**Issue by m3hari** [PointInside/ng2-toastr#99]
I want to toast a message inside my APIService 
```javascript
@Injectable()
export class APIService {
   constructor(){  
   }
   get() { ... }
   update() { ...}
}
```

**how do I import/get ToastManager  instant from this service?.**

I have tried to inject it  as the following 
```javascript
constructor(@Inject(ToastManager) toaster){
} 
```
but it does not work that way.

**Comment by derekshi** [comment]
ToastManager needs `viewContainerRef` in order to inject ToastContainer into DOM. Since service usually doesn't involve any View/DOM element, it's not intended to show toaster in services by design. However, you service can emit any event or expose an Observable to tell your component when to show toaster.

**Comment by narainsagar** [comment]
@meharig Add the below code into the root component of your app: 
```
constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
    this.toastr.setRootViewContainerRef(vRef);
}
```
ref: https://github.com/PointInside/ng2-toastr#breaking-change-solution-for-angular-v22x

**Comment by meharig** [comment]
I got a workaround by emitting an event to a component from the service, the component will do the rendering/showing the toast.  

@derekshi , what do you think about implementing this feature , that we will able to fire toast from services.

I think this is crucial  for several use cases like showing Network error messages from APIService and the like.

**Comment by cebartling** [comment]
There's nothing stopping you from using the ToastsManager from a service.  Just make sure your app's root component sets the RootViewContainerRef and inject the ToastsManager into your service through the constructor and you're set.

**Comment by chriseenberg** [comment]
I did as mentioned - loading 
`constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
    this.toastr.setRootViewContainerRef(vRef);
}` into my app.component and registering the taostmanager into my service, but i keep getting 
`error_handler.js:50 EXCEPTION: Cannot read property 'success' of undefined
ErrorHandler.handleError @ error_handler.js:50
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:233
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:332
error_handler.js:55 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:55
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:233
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:332
`error_handler.js:56 TypeError: Cannot read property 'success' of undefined
    at CatchSubscriber.AuthenticationService.handleError [as selector] (authentication.service.ts:38)
    at CatchSubscriber.error (catch.js:53)
    at MapSubscriber.Subscriber._error (Subscriber.js:128)
    at MapSubscriber.Subscriber.error (Subscriber.js:102)
    at XMLHttpRequest.onLoad (xhr_backend.js:81)
    at ZoneDelegate.invokeTask (zone.js:262)
    at Object.onInvokeTask (ng_zone.js:260)
    at ZoneDelegate.invokeTask (zone.js:261)
    at Zone.runTask (zone.js:151)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:332)`

any ideas to what may cause this?

Thanks.
- Chris

**Comment by kkilton** [comment]
@chriseenberg I got it to work with @cebartling's suggestion like so...

`export class AppComponent implements OnInit {
  constructor(
    public toastr: ToastsManager, 
    private vcr: ViewContainerRef) {
      //this is the only place we need to set this for toasts
      this.toastr.setRootViewContainerRef(vcr);

import { Injectable, ViewContainerRef } from "@angular/core";
import { ToastsManager } from "ng2-toastr";

@Injectable()
export class AlertService {

  constructor(
    private toastr: ToastsManager
  ) { }
}
`
